# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: babalae.BetterGI
PackageVersion: '0.42'
PackageLocale: zh-CN
Publisher: 辉鸭蛋
PublisherUrl: https://www.huiyadan.com/
PublisherSupportUrl: https://github.com/babalae/better-genshin-impact/issues
Author: 辉鸭蛋
PackageName: 更好的原神
PackageUrl: https://bgi.huiyadan.com/
License: GPL-3.0
LicenseUrl: https://github.com/babalae/better-genshin-impact/blob/HEAD/LICENSE
Copyright: Copyright (c) 辉鸭蛋
ShortDescription: BetterGI · 更好的原神， 一个基于计算机视觉技术，意图让原神变的更好的项目。
Description: 📦BetterGI · 更好的原神 - 自动拾取 | 自动剧情 | 全自动钓鱼(AI) | 全自动七圣召唤 | 自动伐木 | 自动刷本 | 自动采集
Moniker: BetterGI
Tags:
- 七圣召唤
- 原神
- 工具箱
- 游戏
- 自动化
- 自动技能
- 自动拾取
- 自动采集
- 自动钓鱼
ReleaseNotes: |-
  - 修复 5.4 版本地图UI变动导致传送失效的问题 @Scarlet1ssimo
  - TP时扩展右上角的不可点击区域，适配新地图UI
  - 修复启动调度器时完全卡死的问题（只会在独占全屏时出现）
  - 修复通知导致的截图失败报错提示
  - 使 JS脚本 中的 keyDown(), keyUp(), keyPress() 方法 和 战斗策略脚本 中的 keydown(), keyup(), keypress() 方法 可以直接使用 虚拟键代码 来执行 鼠标操作 #1124 @2696791698
  - 5.4 七圣召唤卡牌元数据更新 @haokaiyang
ReleaseNotesUrl: https://github.com/babalae/better-genshin-impact/releases/tag/0.42
ManifestType: defaultLocale
ManifestVersion: 1.9.0
