# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Sinew.Enpass
PackageVersion: 6.10.2
PackageLocale: en-US
Publisher: Enpass Technologies Inc.
PublisherUrl: https://www.enpass.io/
PublisherSupportUrl: https://support.enpass.io/
PrivacyUrl: https://www.enpass.io/privacy/
Author: Enpass Technologies Inc.
PackageName: Enpass
PackageUrl: https://www.enpass.io/
License: Proprietary
LicenseUrl: https://www.enpass.io/terms-of-use/
Copyright: Copyright © Enpass Technologies Inc.
ShortDescription: Enpass is a cross-platform password management app to securely store passwords and other credentials in a virtual vault locked with a master password. Unlike most other popular password managers, Enpass is an offline password manager.
Moniker: enpass
Tags:
- credential
- password
- protect
- protection
- security
- vault
PurchaseUrl: https://www.enpass.io/pricing/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
