# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PremiumSoft.NavicatPremium
PackageVersion: 17.3.6
InstallerLocale: id-ID
Platform:
- Windows.Desktop
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- sql
ProductCode: Navicat Premium 17_is1
ReleaseDate: 2025-10-20
AppsAndFeaturesEntries:
- ProductCode: Navicat Premium 17_is1
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\PremiumSoft\Navicat Premium 17'
Installers:
- Architecture: x64
  InstallerUrl: https://download3.navicat.com/download/navicat17_premium_id_x64.exe
  InstallerSha256: 077A0B03D890AC40F8291B21FEEFA276EFB264B60E626D254B29894CDAE8D99B
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://download3.navicat.com/download/navicat17_premium_id_x64.exe
  InstallerSha256: 077A0B03D890AC40F8291B21FEEFA276EFB264B60E626D254B29894CDAE8D99B
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.10.0
