# Created with komac v2.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: JGraph.Draw
PackageVersion: 25.0.2
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
FileExtensions:
- drawio
ReleaseDate: 2024-12-02
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/jgraph/drawio-desktop/releases/download/v25.0.2/draw.io-25.0.2-windows-installer.exe
  InstallerSha256: 9A1E232896FEB2218831D50C34D9B9859E0AE670EFAC662DC52B0EBDF7302982
  ReleaseDate: 2024-12-03
  AppsAndFeaturesEntries:
  - DisplayName: draw.io 25.0.2
    Publisher: JGraph
- Architecture: x86
  InstallerUrl: https://github.com/jgraph/drawio-desktop/releases/download/v25.0.2/draw.io-ia32-25.0.2-windows-32bit-installer.exe
  InstallerSha256: 24412BC241978353A4A025E3A44FBD774359EC47FDEC69CDC389C0D773DD6819
  ReleaseDate: 2024-12-03
  AppsAndFeaturesEntries:
  - DisplayName: draw.io 25.0.2
    Publisher: JGraph
- Architecture: arm64
  InstallerUrl: https://github.com/jgraph/drawio-desktop/releases/download/v25.0.1/draw.io-arm64-25.0.1-windows-arm64-installer.exe
  InstallerSha256: 662BF6AA7B8E790F383D4DE917345CD2BB2D71CB14191A754179773F2F089F28
  ReleaseDate: 2024-12-02
  AppsAndFeaturesEntries:
  - DisplayName: draw.io 25.0.1
    Publisher: JGraph
    DisplayVersion: 25.0.1
ManifestType: installer
ManifestVersion: 1.6.0
