# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Devolutions.Launcher
PackageVersion: 2025.2.26.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- ard
- ftp
- http
- https
- rdp
- sftp
- ssh
- telnet
- vnc
- webdav
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ProductCode: '{6B192B58-78F9-44B9-8505-C63F15C5BE00}'
ReleaseDate: 2025-08-14
AppsAndFeaturesEntries:
- DisplayName: Devolutions Launcher
  ProductCode: '{6B192B58-78F9-44B9-8505-C63F15C5BE00}'
  UpgradeCode: '{CB5FC4EF-9B66-411D-8F6E-2713D2B8F664}'
Installers:
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.Devolutions.Launcher.2025.2.26.0.msi
  InstallerSha256: C0A013D9AD26B9F575A4675E2903CC8EE70B3B8D7D2AB1EDDE0CA8F32EC73857
ManifestType: installer
ManifestVersion: 1.10.0
