# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Docker.DockerDesktop
PackageVersion: 4.27.1
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: install --quiet
  SilentWithProgress: install --quiet
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://desktop.docker.com/win/main/amd64/136059/Docker%20Desktop%20Installer.exe
  InstallerSha256: b4fad4aa2ebbe2dff0728b260d8564ac8a0a7c56794e395b8faa9ff38fab41ee
ManifestType: installer
ManifestVersion: 1.5.0
