# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: TELUS.BusinessConnectPhone
PackageVersion: 25.1.2010.565
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
