# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.PowerBI
PackageVersion: 2.130.754
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 6.2.9200
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: -silent -norestart
  SilentWithProgress: -passive -norestart
  InstallLocation: INSTALLLOCATION="<INSTALLPATH>"
  Log: -log "<LOGPATH>"
  Upgrade: -update
  Custom: ACCEPT_EULA=1
UpgradeBehavior: install
ReleaseDate: 2024-06-11
AppsAndFeaturesEntries:
- DisplayName: Microsoft PowerBI Desktop (x64)
  Publisher: Microsoft Corporation
  ProductCode: '{035c1474-8dc2-474f-8f0f-6edad420b959}'
  InstallerType: burn
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://download.microsoft.com/download/8/8/0/880BCA75-79DD-466A-927D-1ABF1F5454B0/PBIDesktopSetup_x64.exe
  InstallerSha256: AEE1ABBD79083E5E178F44940386D404DCA1AF456AB0DF93D39DC5BA8D31B3B7
ManifestType: installer
ManifestVersion: 1.6.0
