# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Dell.CommandUpdate
PackageVersion: 5.5.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /passthrough /S /V/quiet /V/norestart
  SilentWithProgress: /passthrough /V/passive /V/norestart
  Interactive: /passthrough
  InstallLocation: /V"DELL_COMMAND_UPDATE=\"<INSTALLPATH>\""
  Log: /V"/log \"<LOGPATH>\""
ExpectedReturnCodes:
- InstallerReturnCode: 2
  ReturnResponse: rebootRequiredToFinish
- InstallerReturnCode: 6
  ReturnResponse: rebootInitiated
UpgradeBehavior: install
ProductCode: '{AD1F63E4-F31F-48A2-BB8D-CF7B96CC46A0}'
ReleaseDate: 2025-03-30
AppsAndFeaturesEntries:
- ProductCode: '{AD1F63E4-F31F-48A2-BB8D-CF7B96CC46A0}'
  UpgradeCode: '{E9D40AD1-4E1D-46F2-B44A-F7E98338FCC7}'
  InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://dl.dell.com/FOLDER12925856M/1/Dell-Command-Update-Application_HW0K4_WIN64_5.5.0_A00.EXE
  InstallerSha256: 69C9F7E69180639F19A706B249A77EFE6BC12FFED8BA926328B8C2EEE6C05EC7
ManifestType: installer
ManifestVersion: 1.9.0
