# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 35.0.0-rc1
PackageLocale: en-US
Publisher: Nextcloud GmbH
PublisherUrl: https://nextcloud.com/
PublisherSupportUrl: https://github.com/nextcloud/desktop/issues
PrivacyUrl: https://nextcloud.com/privacy
Author: Nextcloud GmbH
PackageName: Nextcloud
PackageUrl: https://nextcloud.com/
License: GPL-2.0
LicenseUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
Copyright: © 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/nextcloud/desktop/master/COPYING
ShortDescription: The Nextcloud Desktop Client is a tool to synchronize files from Nextcloud Server with your computer.
Description: |-
  Use the desktop clients to keep your files synchronized between your Nextcloud server and your desktop.
  Select one or more directories on your local machine and always have access to your latest files wherever you are.
Moniker: nextclouddesktop
Tags:
- cloud
- cloud-sync
- nextcloud-desktop-client
- synchronization
- utility
ReleaseNotes: |-
  What's Changed
  - chore(macOS): Removed obsolete SwiftNIO dependency by @i2h3 in nextcloud/desktop#10179
  - fix(file-provider): invalidate lock tokens when file paths change. by @camilasan in nextcloud/desktop#10135
  - fix(perf): do not run CI on draft PRs by @Rello in nextcloud/desktop#10183
  - Fix initial menu bar extra sync status by @i2h3 in nextcloud/desktop#10187
  - fix(#10177): Unblock menu bar extra by @i2h3 in nextcloud/desktop#10193
  - Movable wizard window by @i2h3 in nextcloud/desktop#10188
  - fix(gui): prevent nullptr dereference when VFS mode is unavailable by @troed in nextcloud/desktop#10176
  - chore(agents): add guideline for verifiable claims in contributions. by @camilasan in nextcloud/desktop#10200
  - fix(vfs/windows): use proper relative local path for DB records by @mgallien in nextcloud/desktop#10204
  - Relabel "virtual files" as "File Provider" by @i2h3 in nextcloud/desktop#10205
  - fix(libsync): folder move or rename data loss. by @camilasan in nextcloud/desktop#9998
  - fix: build error with OpenSSL 4.0 by @raviksharma in nextcloud/desktop#10223
  - fix(#10216): Prevent app nap and silent kill by @i2h3 in nextcloud/desktop#10230
  - feat(tray): move logout and remove to settings menu by @Rello in nextcloud/desktop#10165
  - fix(UI): read OCC_UPDATE_URL only for dev builds by @Rello in nextcloud/desktop#10236
  - chore(deps): Bump actions/checkout from 6.0.3 to 7.0.0 by @dependabot[bot] in nextcloud/desktop#10225
  - fix(gui): remove gap after status messages by @nilsding in nextcloud/desktop#10245
  - Bugfix/end to end encryption by @mgallien in nextcloud/desktop#10244
  - chore(deps): Bump cpp-linter/cpp-linter-action from 2.18.0 to 2.19.0 by @dependabot[bot] in nextcloud/desktop#10224
  - Correct Remote Change Propagation to File Provider Framework by @i2h3 in nextcloud/desktop#10252
  - Support Adobe Lock Files by @i2h3 in nextcloud/desktop#10260
  - Confine Enumeration (master) by @i2h3 in nextcloud/desktop#10262
  - fix: parsing ] in ignore list in File Provider correctly by @Rello in nextcloud/desktop#10268
  - chore(deps): Bump actions/cache from 5.0.5 to 6.1.0 by @dependabot[bot] in nextcloud/desktop#10273
  - chore(deps): Bump cpp-linter/cpp-linter-action from 2.19.0 to 2.20.0 by @dependabot[bot] in nextcloud/desktop#10275
  - chore(deps): Bump actions/cache/restore from 5.0.5 to 6.1.0 by @dependabot[bot] in nextcloud/desktop#10274
  - chore(deps): Bump actions/setup-python from 6.2.0 to 6.3.0 by @dependabot[bot] in nextcloud/desktop#10271
  - chore(deps): Bump actions/cache/save from 5.0.5 to 6.1.0 by @dependabot[bot] in nextcloud/desktop#10272
  - Remove QtWebEngine by @i2h3 in nextcloud/desktop#10092
  - Fix crash due to FILEPROVIDER_OBSERVER_TOO_MANY_ITEMS by @i2h3 in nextcloud/desktop#10281
  - fix(logs): prints the Qt platform name at startup by @mgallien in nextcloud/desktop#10277
  - fix(cmd,csync): don't silently ignore a missing --exclude file by @mosandlt in nextcloud/desktop#10283
  - Prevent crash on wake (Ticket#96101255) by @i2h3 in nextcloud/desktop#10290
  - chore: disable building with Qt WebEngine in craft settings by @mgallien in nextcloud/desktop#10279
  - "Edit locally" in Web → Reveal in Finder on macOS by @Rello in nextcloud/desktop#10303
  - feature(signup): migrate simple-signup to standard browser by @Rello in nextcloud/desktop#9969
  - chore(deps): Bump nextcloud/pr-feedback-action from 1883b38a033fb16f576875e0cf45f98b857655c4 to c8c97a6b11ff6379e629a8fbde09572730cacec9 by @dependabot[bot] in nextcloud/desktop#10315
  - Bugfix/noid/fix account provisioning by @mgallien in nextcloud/desktop#10304
  - feat(tray): Migrate TrayWindow to the new tray user menu by @Rello in nextcloud/desktop#10164
  - Support Adobe InDesign safe save by @i2h3 in nextcloud/desktop#10322
  - fix: load existing accounts before creating a new one by @mgallien in nextcloud/desktop#10325
  - fix: translation strings by @Rello in nextcloud/desktop#10329
  - fix: Don't recursively call processEvents by @Xaymar in nextcloud/desktop#10314
  - fix(UI): validate E2EE file names by @Rello in nextcloud/desktop#10238
  - fix(exclude): avoid trying to read patterns from file when reading failed by @nilsding in nextcloud/desktop#10335
  - Enable removal of downloaded items on a folder by @i2h3 in nextcloud/desktop#10339
  - fix: "dismiss" string and showing of chat message in tray preview by @Rello in nextcloud/desktop#10343
  - fix(TransifexStringCatalogSanitizer): Hardening to prevent data loss by @i2h3 in nextcloud/desktop#10344
  - feature: add search dialog to new tray menu by @Rello in nextcloud/desktop#10331
  - fix: do not allow scheme change for push notifications by @Rello in nextcloud/desktop#10351
  - Feature/governance labels integration by @mgallien in nextcloud/desktop#10100
  - chore: cleanup some unused capability/sharing methods by @nilsding in nextcloud/desktop#10348
  - perf(sync): remove 3ms scheduling delay between propagation jobs by @qoole in nextcloud/desktop#9992
  - perf(activity): cache singleton pointers and avoid string concat in hot path by @qoole in nextcloud/desktop#9997
  - fix(tray): Fix macOS material choice for tray menu background by @claucambra in nextcloud/desktop#10359
  - Improve FinderSync Extension handling by @i2h3 in nextcloud/desktop#10356
  - Revert "perf(sync): remove 3ms scheduling delay between propagation jobs" by @nilsding in nextcloud/desktop#10371
  - chore(deps): Bump nextcloud/pr-feedback-action from c8c97a6b11ff6379e629a8fbde09572730cacec9 to 4709fa5b3e1821559d4c312ef937b61f1567aa44 by @dependabot[bot] in nextcloud/desktop#10366
  - feat(governance): update governance API for latest changes by @mgallien in nextcloud/desktop#10378
  - chore(deps): Bump actions/stale from 10.3.0 to 10.4.0 by @dependabot[bot] in nextcloud/desktop#10365
  - Check for file provider upload size mismatch by @i2h3 in nextcloud/desktop#10369
  - chore: @claucambra is a new code owner by @mgallien in nextcloud/desktop#10376
  - Improved upload chunk integrity by @i2h3 in nextcloud/desktop#10377
  - Improved file provider switch user experience by @i2h3 in nextcloud/desktop#10354
  - refactor(gui/search): build as a proper QML module by @nilsding in nextcloud/desktop#10360
  - Detect upload conflicts with an If-Match precondition by @i2h3 in nextcloud/desktop#10393
  - feat: Handle AutoCAD lock files in classic sync by @claucambra in nextcloud/desktop#10379
  - feat(fileprovider): Handle AutoCAD lock files by @claucambra in nextcloud/desktop#10372
  - chore: Add performance test/results requirement for perf PRs in PR template by @claucambra in nextcloud/desktop#10390
  - fix(cmd,csync): anchor --exclude patterns at the sync root regardless of filename by @mosandlt in nextcloud/desktop#10284
  - feat: Handle Adobe lock files (InDesign, Premiere) in classic sync by @claucambra in nextcloud/desktop#10367
  - fix(folderwatcher): ignore events for stale inotify watch descriptors by @thstyl2000 in nextcloud/desktop#10389
  - fix(macOS): Prevent stripping of application name components following a dot in Sparkle update notices by @claucambra in nextcloud/desktop#10395
  - fix(file-provider): Remove the misleading size check for uploads again by @i2h3 in nextcloud/desktop#10410
  - Do not vend .allowsExcludingFromSync capability on items by @i2h3 in nextcloud/desktop#10413
  - chore(deps): Bump actions/checkout from 7.0.0 to 7.0.1 by @dependabot[bot] in nextcloud/desktop#10408
  - chore(deps): Bump actions/setup-python from 6.3.0 to 7.0.0 by @dependabot[bot] in nextcloud/desktop#10407
  - feat(ui): Add context menus to text fields by @claucambra in nextcloud/desktop#10406
  - feat: refactor activity window into own folder structure by @Rello in nextcloud/desktop#10350
  - Add a reset button in the app settings by @i2h3 in nextcloud/desktop#10416
  - Bugfix/end to end encryption various fixes by @mgallien in nextcloud/desktop#10414
  - fix: Search and Activity dialog not showing by @Rello in nextcloud/desktop#10433
  - fix(edit-locally): Correctly handle edit-locally request URLs with punycode hosts by @claucambra in nextcloud/desktop#10430
  - feat: Handle Affinity lock files in classic sync by @claucambra in nextcloud/desktop#10417
  - fix(file-provider): Do not continue polling ETag from file provider when account is disabled by @Rello in nextcloud/desktop#10445
  - fix(agents): ensure agents follow proper testing practices by @claucambra in nextcloud/desktop#10447
  - Don't drop all remote changes when one folder read fails by @i2h3 in nextcloud/desktop#10446
  - fix(file-provider): Ensure path comparisons are done on equal normalization by @claucambra in nextcloud/desktop#10443
  - fix(governance): makes desktop UI closer to the files web UI by @mgallien in nextcloud/desktop#10428
  - fix: Prevent DiscoverySingleLocalDirectoryJob from hanging when target is file by @claucambra in nextcloud/desktop#10434
  - Eliminate O(N²) Realm work in large-folder enumeration by @i2h3 in nextcloud/desktop#10466
  - chore(common): print filename if error occurs in file locking check. by @camilasan in nextcloud/desktop#10470
  - fix(macOS): Verify ability to access Local Network by @claucambra in nextcloud/desktop#10460
  - fix(activity): File details menu fixes by @claucambra in nextcloud/desktop#10480
  - fix(propagateupload): ensure file size stays the same for new uploads by @nilsding in nextcloud/desktop#9823
  - fix(tray): simplify disconnected account menu by @Rello in nextcloud/desktop#10461
  - fix: update Sonarcloud settings by @Rello in nextcloud/desktop#10498
  - fix(filesystem): do not attempt to lock directories on Windows by @andreasbohl in nextcloud/desktop#10487
  - fix(discovery): move file lock state off the GUI thread. by @camilasan in nextcloud/desktop#10500
  - Refactored XPC for FinderSync Extension by @i2h3 in nextcloud/desktop#10492
  - fix(macOS): use tag to pass menu command to Finder extension. by @camilasan in nextcloud/desktop#10528
  - chore(deps): Bump actions/stale from 10.4.0 to 11.0.0 by @dependabot[bot] in nextcloud/desktop#10530
ReleaseNotesUrl: https://github.com/nextcloud-releases/desktop/releases/tag/v35.0.0-rc1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
