# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.DotNet.DesktopRuntime.9
PackageVersion: 9.0.7
PackageLocale: en-US
Publisher: Microsoft Corporation
PackageName: Microsoft .NET Windows Desktop Runtime 9.0
PackageUrl: https://dotnet.microsoft.com/
License: MIT
ShortDescription: .NET is a free, cross-platform, open-source developer platform for building many different types of applications.
Moniker: dotnet-desktop-9
Tags:
- .NET
- .NET Core
- C#
- F#
- VB
- Visual Basic
- Windows
- Windows Desktop
- csharp
- dotnet
- fsharp
- net
- runtime
ManifestType: defaultLocale
ManifestVersion: 1.10.0
