# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Google.Chrome
PackageVersion: 119.0.6045.160
InstallerLocale: en-US
InstallerType: msi
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
AppsAndFeaturesEntries:
- UpgradeCode: '{C1DFDF69-5945-32F2-A35E-EE94C99C7CF4}'
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: F5BA5308C245F2F5B8288B409B08842DA1B081F36A5F87F4E60DE50E2AFE3AB1
  ProductCode: '{90ED09E5-8842-3CD3-A477-76FEDA344E5F}'
- Architecture: x86
  Scope: machine
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise.msi
  InstallerSha256: F5BA5308C245F2F5B8288B409B08842DA1B081F36A5F87F4E60DE50E2AFE3AB1
  ProductCode: '{90ED09E5-8842-3CD3-A477-76FEDA344E5F}'
- Architecture: x64
  Scope: user
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 08D01F0BBE85785058695F76083BEB7EBD971D00867ED07A565946408F1B844B
  ProductCode: '{19B37A31-CC51-332C-AB5D-860490DA5960}'
- Architecture: x64
  Scope: machine
  InstallerUrl: https://dl.google.com/dl/chrome/install/googlechromestandaloneenterprise64.msi
  InstallerSha256: 08D01F0BBE85785058695F76083BEB7EBD971D00867ED07A565946408F1B844B
  ProductCode: '{19B37A31-CC51-332C-AB5D-860490DA5960}'
ManifestType: installer
ManifestVersion: 1.5.0
