# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: AmN.yasb
PackageVersion: 1.6.0
PackageLocale: en-US
Publisher: AmN
PublisherUrl: https://github.com/amnweb
PublisherSupportUrl: https://github.com/amnweb/yasb/issues
Author: AmN
PackageName: yasb
PackageUrl: https://github.com/amnweb/yasb
License: MIT License
LicenseUrl: https://github.com/amnweb/yasb/blob/HEAD/LICENSE
Copyright: Copyright 2024 AmN. All rights reserved.
CopyrightUrl: https://github.com/amnweb/yasb/blob/main/LICENSE
ShortDescription: A configurable Windows status bar.
Description: A configurable Windows status bar.
Tags:
- status bar
- topbar
ReleaseNotes: |-
  New Features
  - implement Cava widget with customizable options 5940ef1
  - connect aboutToQuit signal to stop taskbar widget events ef15a07
  Bugfixes
  - correct syntax error in winget update command 0777216
  - hide widget when API key or location is missing be368da
  - update font family in default styles.css 1e1225a
  - update PyQt6 version to >=6.8.0 c5ba37f
  - update build version to 1.6.0 6176c3b
  Refactors
  - comment out debug logging for weather data 2d9825a
  Documentation Changes
  - add Cava widget documentation and update sidebar bdb1d8b
  Important
  YASB now reads font names in the same way as Windows. For example, the old font-family: "JetBrainsMono NFP" has become font-family: "JetBrainsMono Nerd Font Propo". To get the correct font name, open the font settings in Windows and copy the font name from there.
  Full Changelog: v1.5.91...v1.6.0
ReleaseNotesUrl: https://github.com/amnweb/yasb/releases/tag/v1.6.0
InstallationNotes: https://github.com/amnweb/yasb
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/amnweb/yasb/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
