# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Armin2208.WindowsAutoNightMode
PackageVersion: 10.4.2.29
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: uninstallPrevious
ProductCode: '{470BC918-3740-4A97-9797-8570A7961130}_is1'
ReleaseDate: 2025-01-24
AppsAndFeaturesEntries:
- ProductCode: '{470BC918-3740-4A97-9797-8570A7961130}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/10.4.2.29/AutoDarkModeX_10.4.2.29_ARM64.exe
  InstallerSha256: 5CB18E96EA5129F5C60169819E74EB6E41CCA774373B82B1C4323295FB635FE4
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/releases/download/10.4.2.29/AutoDarkModeX_10.4.2.29_ARM64.exe
  InstallerSha256: 5CB18E96EA5129F5C60169819E74EB6E41CCA774373B82B1C4323295FB635FE4
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\AutoDarkMode'
ManifestType: installer
ManifestVersion: 1.9.0
