# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: NotionRepackaged.NotionEnhanced
PackageVersion: 2.0.18
InstallerLocale: en-US
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: 59a5db67-d528-5cad-9dc9-4012b8118e47
ReleaseDate: 2021-12-31
AppsAndFeaturesEntries:
- DisplayName: Notion Enhanced 2.0.18-1
  DisplayVersion: 2.0.18-1
  ProductCode: 59a5db67-d528-5cad-9dc9-4012b8118e47
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-Setup-2.0.18-1.exe
  InstallerSha256: 72DA3BF4D83462D57A54715814C0B8B1EF9A50739E7461381EA6A595256516EE
  InstallerSwitches:
    Custom: /CurrentUser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/notion-enhancer/notion-repackaged/releases/download/v2.0.18-1/Notion-Enhanced-Setup-2.0.18-1.exe
  InstallerSha256: 72DA3BF4D83462D57A54715814C0B8B1EF9A50739E7461381EA6A595256516EE
  InstallerSwitches:
    Custom: /AllUsers
ManifestType: installer
ManifestVersion: 1.9.0
