# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Telegram.TelegramDesktop
PackageVersion: 5.5.3
InstallModes:
- interactive
- silent
- silentWithProgress
Protocols:
- tg
Installers:
- Architecture: x64
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v5.5.3/tsetup-x64.5.5.3.exe
  InstallerSha256: 706D8A06C3E99457AF4EE6C66C79E2BAD6C0C269282BC922EE88BD7F7E0DCFBD
  UpgradeBehavior: install
- Architecture: x86
  InstallerType: inno
  Scope: user
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v5.5.3/tsetup.5.5.3.exe
  InstallerSha256: DB537C3D68A7044D2E9FE5B7BEE28F71D0072FB1923DB5E708A3E2A4FAFDFBE1
  UpgradeBehavior: install
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Telegram\Telegram.exe
    PortableCommandAlias: Telegram.exe
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v5.5.3/tportable-x64.5.5.3.zip
  InstallerSha256: 8D4C7C4955DB827618B1C51EB1EAA7EDFE367A3BC1BCA8E89250775CBF84FB75
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: Telegram\Telegram.exe
    PortableCommandAlias: Telegram.exe
  InstallerUrl: https://github.com/telegramdesktop/tdesktop/releases/download/v5.5.3/tportable.5.5.3.zip
  InstallerSha256: 76896A958E1F5F3085EF1E3295DB95894C37223D9C36E5BBFC094207C1744B28
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2024-09-10
