# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: JetBrains.Toolbox
PackageVersion: 2.2.0.19611
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Protocols:
- jetbrains
ProductCode: Toolbox
Installers:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/toolbox/jetbrains-toolbox-2.2.0.19611.exe
  InstallerSha256: 42E92A0BE86957436824F3D7C060097495628D82E4FE45FDB7DFDE1B4B5FD71D
ManifestType: installer
ManifestVersion: 1.5.0
