# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Cisco.CiscoWebexMeetings
PackageVersion: 43.12.2.4
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{31AB8532-A8B9-D7CD-65BC-5CFD2B8A68E9}'
ReleaseDate: 2023-12-29
AppsAndFeaturesEntries:
- UpgradeCode: '{C599642D-7A3F-4351-ADC5-2BA171B6451E}'
Installers:
- Architecture: x64
  InstallerUrl: https://akamaicdn.webex.com/client/webexapp.msi
  InstallerSha256: FDD7485880F46B8B5A0F99777612FBB532BA4913A1F42BB75A55ECA5A863996D
ManifestType: installer
ManifestVersion: 1.5.0
