# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: anatawa12.ALCOM
PackageVersion: 1.9.0
InstallerLocale: en-US
InstallerType: nullsoft
ProductCode: ALCOM
ReleaseDate: 2025-01-01
AppsAndFeaturesEntries:
- ProductCode: ALCOM
InstallationMetadata:
  DefaultInstallLocation: placeholder\ALCOM
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/vrc-get/vrc-get/releases/download/v1.9.0/x86_64-pc-windows-msvc-vrc-get.exe
  InstallerSha256: C4F8814EAC3DAD86397814CDA3E1D4CC11B9F4377F53B4405F750D68D223D561
ManifestType: installer
ManifestVersion: 1.9.0
