# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: JetBrains.Rider
PackageVersion: 2023.3.3
PackageLocale: en-US
Publisher: JetBrains s.r.o.
PublisherUrl: https://www.jetbrains.com/
PublisherSupportUrl: https://www.jetbrains.com/support/
PrivacyUrl: https://www.jetbrains.com/legal/docs/privacy/privacy/
Author: JetBrains s.r.o.
PackageName: JetBrains Rider
PackageUrl: https://www.jetbrains.com/rider/
License: Proprietary
LicenseUrl: https://www.jetbrains.com/legal/docs/toolbox/user/
Copyright: Copyright © 2000-2023 JetBrains s.r.o.
ShortDescription: Fast & powerful cross-platform .NET IDE
Description: Develop .NET, ASP.NET, .NET Core, Xamarin or Unity applications on Windows, Mac, Linux
Moniker: rider
Tags:
- .net
- asp.net
- c#
- code
- coding
- develop
- development
- dotnet
- ide
- programming
- unity
- xamarin
PurchaseUrl: https://www.jetbrains.com/rider/buy/
Documentations:
- DocumentLabel: Learning Rider
  DocumentUrl: https://www.jetbrains.com/rider/documentation/
ManifestType: defaultLocale
ManifestVersion: 1.5.0
