# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Okta.OktaVerify
PackageVersion: 7.0.1.0
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
AppsAndFeaturesEntries:
- ProductCode: '{008b801f-b8a1-40df-911b-a77c60e029c7}'
  UpgradeCode: '{0C7A600D-1916-410A-A7A1-99A902523D3A}'
  InstallerType: burn
Installers:
- Architecture: x86
  InstallerUrl: https://okta.okta.com/artifacts/WINDOWS_OKTA_VERIFY/7.0.1.0/OktaVerifySetup-7.0.1.0-15bb87b.exe
  InstallerSha256: F1FE7E154E5AC84AE6034B55C91FA627312C01D9B58041C2076BADACF58AADD2
ManifestType: installer
ManifestVersion: 1.12.0
