# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: BlenderFoundation.Blender
PackageVersion: 4.0.1
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- 3ds
- fbx
- glb
- gltf
- obj
- ply
- stl
ProductCode: '{B557A37F-811D-4A98-9306-FB34E069D999}'
Installers:
- Architecture: x64
  InstallerUrl: https://ftp.nluug.nl/pub/graphics/blender/release/Blender4.0/blender-4.0.0-windows-x64.msi
  InstallerSha256: C1B8BB8907A329DA200BF0D457748F3DA86C2D1A204BBCD0BE3BCCDE7E056EF0
ManifestType: installer
ManifestVersion: 1.5.0
