# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: creativeprojects.resticprofile
PackageVersion: 0.29.1
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: resticprofile.exe
Commands:
- resticprofile
ReleaseDate: 2025-02-06
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/creativeprojects/resticprofile/releases/download/v0.29.1/resticprofile_0.29.1_windows_386.zip
  InstallerSha256: 29A57D3304B801371BC4D85CA67684C84B162BEAA2B00938101C1650133B26C3
- Architecture: x64
  InstallerUrl: https://github.com/creativeprojects/resticprofile/releases/download/v0.29.1/resticprofile_0.29.1_windows_amd64.zip
  InstallerSha256: E0FFDF93199736F6D4ACECD66BAC97807E8D54DF3FDED4C1D1B074B421F98576
- Architecture: arm64
  InstallerUrl: https://github.com/creativeprojects/resticprofile/releases/download/v0.29.1/resticprofile_0.29.1_windows_arm64.zip
  InstallerSha256: 0FD8FDC756CCA2BBDC22FFAD01BC61BC781D1EF29AD4858302647114A5FD11DA
ManifestType: installer
ManifestVersion: 1.9.0
