# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: creativeprojects.resticprofile
PackageVersion: 0.29.1
PackageLocale: en-US
Publisher: creativeprojects
PublisherUrl: https://creativeprojects.tech/
PublisherSupportUrl: https://github.com/creativeprojects/resticprofile/issues
Author: Fred
PackageName: resticprofile
PackageUrl: https://creativeprojects.github.io/resticprofile
License: GPL-3.0
LicenseUrl: https://github.com/creativeprojects/resticprofile/blob/HEAD/LICENSE
ShortDescription: Configuration profiles manager and scheduler for restic backup
Moniker: resticprofile
Tags:
- backup
- restic
ReleaseNotes: |-
  ❄️ Small maintenance release ☃️
  Not much going on in this maintenance release while I'm still working on a big refactoring of the scheduling for the next release.
  - logrotate package added to the Docker image
  - upgrade dependencies to fix security vulnerabilities
  Changelog
  - e2297a6 add logrotate to docker image #440
  - 37c9aef upgrade package - CVE-2024-45337
  - 467b82e upgrade packages
ReleaseNotesUrl: https://github.com/creativeprojects/resticprofile/releases/tag/v0.29.1
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://creativeprojects.github.io/resticprofile
- DocumentLabel: Restic documentation
  DocumentUrl: https://restic.readthedocs.io/
ManifestType: defaultLocale
ManifestVersion: 1.9.0
