# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: GNU.MidnightCommander
PackageVersion: 4.8.31.230
PackageLocale: en-US
Publisher: The Free Software Foundation, Inc.
PublisherUrl: https://midnight-commander.org/
PublisherSupportUrl: https://github.com/adamyg/mcwin32/issues
Author: The Free Software Foundation, Inc.
PackageName: GNU Midnight Commander
PackageUrl: https://midnight-commander.org/
License: GPL3
LicenseUrl: https://github.com/MidnightCommander/mc/blob/master/doc/COPYING
CopyrightUrl: https://github.com/MidnightCommander/mc/blob/master/doc/COPYING
ShortDescription: GNU Midnight Commander is a visual file manager, licensed under GNU General Public License and therefore qualifies as Free Software.
Description: |-
  GNU Midnight Commander is a visual file manager, licensed under GNU General Public License and therefore qualifies as Free Software.
  It's a feature rich full-screen text mode application that allows you to copy, move and delete files and whole directory trees, search for files and run commands in the subshell.
  Internal viewer and editor are included.
Moniker: mc
Tags:
- file-manager
- fm
- mc
ReleaseNotes: |-
  build-230:
  - mc merge 4.8.31 (#70)
  - mbedtls 3.5.2 (#67)
  - AltGr detection (#71, #52)
  - mcdiff integration (#74)
  - cd/cdpath (#72)
  x64 binary (Beta)
ReleaseNotesUrl: https://github.com/adamyg/mcwin32/releases/tag/4.8.31.230
ManifestType: defaultLocale
ManifestVersion: 1.9.0
