# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: mmanela.markdownoutlook
PackageVersion: 1.2.0
InstallerLocale: en-US
InstallerType: msi
Scope: user
ProductCode: '{4F59BA55-A58C-425D-A743-4D3D1B5756BC}'
ReleaseDate: 2021-12-08
AppsAndFeaturesEntries:
- DisplayVersion: 1.0.0
  ProductCode: '{4F59BA55-A58C-425D-A743-4D3D1B5756BC}'
  UpgradeCode: '{DB5C72A6-2A12-4AE5-9F10-6ED9F802997E}'
InstallationMetadata: {}
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/mmanela/MarkdownOutlook/releases/download/v1.2.0/MarkdownOutlookSetup.msi
  InstallerSha256: 9FAB92B0AFB4D0AFF0E7FAB403F0DF384628F1AEDE37FF5CFCD21D97D468490F
ManifestType: installer
ManifestVersion: 1.9.0
