# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: VaclavSlavik.Poedit
PackageVersion: 3.6.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
FileExtensions:
- po
- pot
ProductCode: '{68EB2C37-083A-4303-B5D8-41FA67E50B8F}_is1'
ReleaseDate: 2025-03-31
AppsAndFeaturesEntries:
- Publisher: Vaclav Slavik
  ProductCode: '{68EB2C37-083A-4303-B5D8-41FA67E50B8F}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Poedit'
Installers:
- Architecture: x64
  InstallerUrl: https://download.poedit.net/Poedit-3.6-setup.exe
  InstallerSha256: 39546BD7AD2712EF4A7EF832466490325365FB441508E1CE5A1C1DFF590507DE
  InstallerSwitches:
    Custom: /ALLUSERS
- Architecture: x64
  InstallerUrl: https://download.poedit.net/Poedit-3.6-setup.exe
  InstallerSha256: 39546BD7AD2712EF4A7EF832466490325365FB441508E1CE5A1C1DFF590507DE
  InstallerSwitches:
    Custom: /CURRENTUSER
ManifestType: installer
ManifestVersion: 1.9.0
