# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.Edge
PackageVersion: 154.0.4258.53
InstallerLocale: en-US
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: msi
Scope: machine
Protocols:
- http
- https
FileExtensions:
- crx
- htm
- html
- pdf
- url
AppsAndFeaturesEntries:
- UpgradeCode: '{883C2625-37F7-357F-A0F4-DFAF391B2B9C}'
Installers:
- Architecture: x64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/ded68157-46e9-4336-a3b0-67ad31f3ea2c/MicrosoftEdgeEnterpriseX64.msi
  InstallerSha256: 548E0700390FFD93545F40A8BAE1489FAEE3536F84CD7935BAB5A087F3758F36
  ProductCode: '{04EDB555-11E1-322E-89F1-F1E4542CD53E}'
- Architecture: x86
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/3bf433ec-3d78-4b7c-999a-af447d100f35/MicrosoftEdgeEnterpriseX86.msi
  InstallerSha256: F4DF9A7A8BEA5AD19078A57CE354C363007BC70431EDE4263DE324B1E4C635E6
  ProductCode: '{AC206CD4-D939-31FE-9B56-990E8B4DEAA1}'
- Architecture: arm64
  InstallerUrl: https://msedge.sf.dl.delivery.mp.microsoft.com/filestreamingservice/files/775c1987-4313-4e6f-84a3-9a3c670b8455/MicrosoftEdgeEnterpriseARM64.msi
  InstallerSha256: E42676A1874AB866910F2F0FEB8A3092A2B12EE3F7790F53346CE08C5215B16A
  ProductCode: '{067EEF7D-516A-3D04-909E-2914FCDD37BC}'
ManifestType: installer
ManifestVersion: 1.12.0
