# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: TechSmith.Camtasia
PackageVersion: 25.0.0.7062
MinimumOSVersion: 10.0.19042.0
InstallerType: burn
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- camtasiaauth24
- techsmithcamtasia
FileExtensions:
- campackage
- camshortcuts
- camtemplate
- camtheme
- kissyproj
- libzip
- trec
- tscdf
- tscproj
- tscprojzip
- tscshadervid
- tsctemplate
ReleaseDate: 2025-02-10
Installers:
- Architecture: neutral
  InstallerUrl: https://download.techsmith.com/camtasiastudio/releases/2500/camtasia.exe
  InstallerSha256: CEF2EF836EF996439F68AF069007E7A51448F721A914BE8D74834A84D442E437
  ProductCode: '{1ad3c46d-6a86-498c-912e-ce35e4728709}'
  ElevationRequirement: elevatesSelf
- Architecture: neutral
  InstallerUrl: https://download.techsmith.com/camtasiastudio/releases/2500/camtasia.exe
  InstallerSha256: CEF2EF836EF996439F68AF069007E7A51448F721A914BE8D74834A84D442E437
  InstallModes:
  - silent
  - silentWithProgress
  Dependencies:
    PackageDependencies:
    - PackageIdentifier: Microsoft.EdgeWebView2Runtime
    - PackageIdentifier: Microsoft.VCRedist.2015+.x64
  ProductCode: '{CD0B0AD5-8922-4674-AFF9-55C8D2D8F900}'
ManifestType: installer
ManifestVersion: 1.9.0
