# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: ZelloInc.Zello
PackageVersion: 16.1.0.0
PackageLocale: en-US
Publisher: Zello Inc
PackageName: Zello
License: Freeware
ShortDescription: 'Zello is the world’s #1 ranked push-to-talk app.'
ManifestType: defaultLocale
ManifestVersion: 1.9.0
