# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: 2dust.v2rayN.Pre-release
PackageVersion: 7.7.1
PackageLocale: en-US
Publisher: 2dust
PublisherUrl: https://github.com/2dust
PublisherSupportUrl: https://github.com/2dust/v2rayN/issues
PackageName: v2rayN
PackageUrl: https://github.com/2dust/v2rayN
License: GPL-3.0
LicenseUrl: https://github.com/2dust/v2rayN/blob/HEAD/LICENSE
ShortDescription: A GUI client for Windows, support Xray core and v2fly core and others
Tags:
- proxy
- shadowsocks
- socks5
- trojan
- v2fly
- v2ray
- vless
- vmess
- windows
- xray
- xtls
ReleaseNotes: |-
  本次更新
  - 重构代码结构，界面和业务解耦（后面可能可跨平台，比如linux）
  - 分组中增加自定义配置的socks端口
  - 独立包检查更新时将会提示手动下载
  - 给xray-core 和 sing-box-core 增加更多mux参数
  - Wiki增加不显示的参数的说明 https://github.com/2dust/v2rayN/wiki/Description-of-some-parameters
  - 检查更新改进，现在可一键更新所有
  - PAC文件更新 #5636
  注意
  因为go v1.21以后不支持windows7 系统，所以所有最新core在windows7上可能运行失败；
  解决办法是去下载对应特殊的core，比如写了 win7 https://github.com/XTLS/Xray-core/releases/tag/v1.8.24
  发布文件介绍，不知道下载哪个文件的请看
ReleaseNotesUrl: https://github.com/2dust/v2rayN/releases/tag/6.57
ManifestType: defaultLocale
ManifestVersion: 1.9.0
