# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Amulet.Amulet
PackageVersion: 1.21.11
PackageLocale: en-US
Publisher: Amulet
PublisherUrl: https://github.com/ianmaclarty
PackageName: Amulet
PackageUrl: https://github.com/ianmaclarty/amulet
License: MIT
LicenseUrl: https://github.com/ianmaclarty/amulet/blob/HEAD/LICENSE
ShortDescription: Amulet is a Lua-based audio/visual toolkit designed for small games and experimentation.
ReleaseNotes: |-
  Please note, this is the first release using Github Actions. Previous releases were built with Travis and Appveyor, but those have long since stopped working. Unfortunately I didn't have time to port the windows and mac installer packages, but the zips are still available. I also wasn't able to get the emscripted (html) build working, so, for now, please use previous releases for that. I also wasn't able to build on the new ARM Macs yet, so the macos release still targets intel (which is what I own), for now.
  Changes between v1.21.10 and v1.21.11:
  5a40b93 Allow loading data.pak from a different url via window.amulet_data_pak_url
  48b85c2 add native file open dialog (windows only for now)
  2689984 fix build error on mac and linux
  b9f61f3 fix error in mingw build
  7cf648f disable native file open dialog on mingw to avoid link error
  084afdf Merge pull request #137 from jminor/external_data_pak
  b483259 @ character at beginning of resource to load now forces it to be loaded from filesystem, without prepending data dir path
  8fa43fc upgrade stb_image to get 16 bit png support
  b0e8b28 minor documentation fixes
  99f1a36 revert city.lua changes
  3d1363e Merge pull request #139 from selvan/master
  328dd7b Add documentation for am.type
  4090c8d Merge pull request #140 from churchianity/master
  92a9d60 add documentation for am.rand
  f5791fd Merge pull request #142 from churchianity/am_rand
  ecf02fe Add bindings setting to am.postprocess
  67cb615 Add documentation for the new settings field: bindings
  5cabf42 Expose bindings field for am.postprocess
  4a7cf2d Merge pull request #143 from InquisitivePenguin/postprocess-bindings
  26e8ba2 target android sdk 34 by default
ReleaseNotesUrl: https://github.com/ianmaclarty/amulet/releases/tag/v1.21.11
ManifestType: defaultLocale
ManifestVersion: 1.9.0
