# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Oracle.JavaRuntimeEnvironment
PackageVersion: 8.0.4210.9
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /s REBOOT=0
  SilentWithProgress: /s REBOOT=0
  InstallLocation: INSTALLDIR=<INSTALLPATH>
  Custom: SPONSORS=0 AUTO_UPDATE=0
UpgradeBehavior: uninstallPrevious
Commands:
- java
FileExtensions:
- class
- idx
- jad
- jar
- java
- jsp
ReleaseDate: 2024-06-17
Installers:
- Architecture: x86
  InstallerUrl: https://javadl.oracle.com/webapps/download/GetFile/1.8.0_421-b09/d8aa705069af427f9b83e66b34f5e380/windows-i586/jre-8u421-windows-i586.exe
  InstallerSha256: 002C72EB230946FF5ABAB1FBDC7AA7617F38024F198CA6679E5E6EF558FA1BED
- Architecture: x64
  InstallerUrl: https://javadl.oracle.com/webapps/download/GetFile/1.8.0_421-b09/d8aa705069af427f9b83e66b34f5e380/windows-i586/jre-8u421-windows-i586.exe
  InstallerSha256: 002C72EB230946FF5ABAB1FBDC7AA7617F38024F198CA6679E5E6EF558FA1BED
ManifestType: installer
ManifestVersion: 1.6.0
