# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: TortoiseSVN.TortoiseSVN
PackageVersion: 1.14.6.29673
InstallerLocale: en-US
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Upgrade: /norestart
  Custom: /norestart
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://master.dl.sourceforge.net/project/tortoisesvn/1.14.5/Application/TortoiseSVN-1.14.6.29673-win32-svn-1.14.3.msi/download
  InstallerSha256: 8CF5CE27D21490C24EEDF91E0AC2BC4A748BA8F4EB20CB7C1FC9442D2D580008
  UnsupportedOSArchitectures:
  - x64
  - arm64
- Architecture: x64
  InstallerUrl: https://master.dl.sourceforge.net/project/tortoisesvn/1.14.5/Application/TortoiseSVN-1.14.6.29673-x64-svn-1.14.3.msi/download
  InstallerSha256: 8CF5CE27D21490C24EEDF91E0AC2BC4A748BA8F4EB20CB7C1FC9442D2D580008
  ProductCode: '{E6F481E7-EF30-4811-A73C-1379B2C94595}'
  UnsupportedOSArchitectures:
  - x86
  - arm64
- Architecture: arm64
  InstallerUrl: https://master.dl.sourceforge.net/project/tortoisesvn/1.14.5/Application/TortoiseSVN-1.14.6.29673-ARM64-svn-1.14.3.msi/download
  InstallerSha256: 8CF5CE27D21490C24EEDF91E0AC2BC4A748BA8F4EB20CB7C1FC9442D2D580008
  UnsupportedOSArchitectures:
  - x64
  - x86
ManifestType: installer
ManifestVersion: 1.5.0
