# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: OpenRPAApS.OpenRPA
PackageVersion: 1.4.57.11
PackageLocale: en-US
Publisher: OpenRPA ApS
PublisherUrl: https://github.com/open-rpa
Author: OpenRPA ApS
PackageName: OpenRPA
PackageUrl: https://github.com/open-rpa/openrpa
License: MPL-2.0
LicenseUrl: https://github.com/open-rpa/openrpa/blob/HEAD/LICENSE
CopyrightUrl: https://raw.githubusercontent.com/open-rpa/openrpa/master/LICENSE
ShortDescription: Free Open Source Enterprise Grade RPA
Tags:
- automation
- iiot
- iot
- multiple-robots
- openflow
- rpa
- workflow
ReleaseNotes: |-
  What's Changed
  - Fix logging attributes by @skadefro in #794
  Full Changelog: 1.4.57.10...1.4.57.11
ReleaseNotesUrl: https://github.com/open-rpa/openrpa/releases/tag/1.4.57.11
Documentations:
- DocumentLabel: OpenIAP Docs
  DocumentUrl: https://docs.openiap.io/
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/open-rpa/openrpa/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
