# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Cisco.CiscoWebexMeetings
PackageVersion: 45.2.1.2
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{ECE29ADA-DB73-59AA-BA90-CF45147C7DBE}'
ReleaseDate: 2025-02-18
AppsAndFeaturesEntries:
- ProductCode: '{ECE29ADA-DB73-59AA-BA90-CF45147C7DBE}'
  UpgradeCode: '{C599642D-7A3F-4351-ADC5-2BA171B6451E}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Webex\.'
Installers:
- Architecture: x86
  InstallerUrl: https://akamaicdn.webex.com/client/webexapp.msi
  InstallerSha256: 644555D63D416C86DDE9E2427AF04F9C32C0F8DE6D33F6A1322A5215038EBAA0
ManifestType: installer
ManifestVersion: 1.9.0
