# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Cisco.CiscoWebexMeetings
PackageVersion: 45.2.1.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
