# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Nextcloud.NextcloudDesktop
PackageVersion: 3.14.3
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Custom: Reboot=ReallySuppress
InstallerSuccessCodes:
- 3010
UpgradeBehavior: install
ProductCode: '{9E6BEFC8-CED4-4823-AC9C-C3ED3B670905}'
AppsAndFeaturesEntries:
- DisplayName: Nextcloud
  Publisher: Nextcloud GmbH
  DisplayVersion: 3.14.2.20241018
  ProductCode: '{6D2A9BBA-60AC-4EB6-A2E1-AC45F84A6C07}'
  UpgradeCode: '{FD2FCCA9-BB8F-4485-8F70-A0621B84A7F4}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Nextcloud'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/nextcloud-releases/desktop/releases/download/v3.14.1/Nextcloud-3.14.1-x64.msi
  InstallerSha256: E9E956B8065B95F5C03CC4CF4AF1683B5D1AB24BC3F3DF125FF7D70DEEF1F896
ManifestType: installer
ManifestVersion: 1.6.0
ReleaseDate: 2024-09-27
