# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Citrix.Workspace
PackageVersion: 24.5.11.31
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent /norestart
  SilentWithProgress: /silent /norestart
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- receiver
FileExtensions:
- cr
- ica
ProductCode: CitrixOnlinePluginPackWeb
Installers:
- Architecture: x86
  InstallerUrl: https://downloadplugins.citrix.com/ReceiverUpdates/Prod/Receiver/Win/CitrixWorkspaceApp24.5.11.31.exe
  InstallerSha256: 6EF90C5E3A45ABE7EB28374C91ECCE4DFE8EA61AADBAE0149285027D833B1561
ManifestType: installer
ManifestVersion: 1.6.0
