# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GLPI-Project.GLPI-Agent
PackageVersion: "1.10"
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
Commands:
- glpi-agent
ProductCode: '{1CFB6EE6-6BF5-1014-B525-EBCD8FA69B29}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/glpi-project/glpi-agent/releases/download/1.10/GLPI-Agent-1.10-x64.msi
  InstallerSha256: 2EA2300A2E79C5927E283F111D5D1E5FF47E132F1660A6B41DAB49933FFD09AE
ManifestType: installer
ManifestVersion: 1.6.0
