# Created with komac v2.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Mozilla.Firefox.ESR
PackageVersion: 128.7.0
InstallerType: exe
Scope: machine
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
FileExtensions:
- avif
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
ReleaseDate: 2025-02-03
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/128.7.0esr/win32/en-US/Firefox%20Setup%20128.7.0esr.exe
  InstallerSha256: 01502498996DC77EDD5A473874DEE118DD29381B32300808A0AC4A73828648B9
  ProductCode: Mozilla Firefox 128.6.0 ESR (arm64 en-US)
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/128.7.0esr/win32/en-US/Firefox%20Setup%20128.7.0esr.exe
  InstallerSha256: 01502498996DC77EDD5A473874DEE118DD29381B32300808A0AC4A73828648B9
  ProductCode: Mozilla Firefox 128.6.0 ESR (x86 en-US)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/firefox/releases/128.7.0esr/win64/en-US/Firefox%20Setup%20128.7.0esr.exe
  InstallerSha256: EEC2853A3DAE71D27BE136AC163F1F8DBFB65608954AF2E966EBA7998E6AFCCE
  ProductCode: Mozilla Firefox 128.6.0 ESR (x64 en-US)
ManifestType: installer
ManifestVersion: 1.9.0
