# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: OpenGMK.GM8Decompiler.GNU
PackageVersion: 2.2.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: gm8decompiler.exe
ReleaseDate: 2024-02-12
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/OpenGMK/GM8Decompiler/releases/download/v2.2.0/gm8decompiler-v2.2.0-i686-pc-windows-msvc.zip
  InstallerSha256: 9C38E852559304D2840934B0DA2ED8595517F22FA198FC064AC06DA3DBF9EEE7
- Architecture: x64
  InstallerUrl: https://github.com/OpenGMK/GM8Decompiler/releases/download/v2.2.0/gm8decompiler-v2.2.0-x86_64-pc-windows-msvc.zip
  InstallerSha256: A68A4CDBD455A2164885C8D854E5F7891324043CDDAD19B80BF1D9C4D958A860
ManifestType: installer
ManifestVersion: 1.9.0
