# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: evernote.evernote
PackageVersion: 10.65.3
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: EE1D5BB2DFD08A334077CA4646FD03791B985790891E189D4F5AD533419B1F27
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: EE1D5BB2DFD08A334077CA4646FD03791B985790891E189D4F5AD533419B1F27
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
