# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: Hanthor.BluefinCLI
PackageVersion: 0.11.8
PackageLocale: en-US
Publisher: Hanthor
PublisherUrl: https://github.com/tuna-os
PublisherSupportUrl: https://github.com/tuna-os/bluefin-cli/issues
PackageName: BluefinCLI
PackageUrl: https://github.com/tuna-os/bluefin-cli
License: Apache-2.0
LicenseUrl: https://github.com/tuna-os/bluefin-cli/blob/main/LICENSE
Copyright: Copyright 2025 Bluefin CLI contributors
ShortDescription: Modern CLI for managing shell config and dev environment customization on Universal Blue.
Moniker: BluefinCLI
Tags:
- cli
- shell
- bluefin
- universal-blue
ReleaseNotes: |-
  ## [0.11.8](https://github.com/tuna-os/bluefin-cli/compare/v0.11.7...v0.11.8) (2026-10-10)


  ### Bug Fixes

  • **deps:** update module golang.org/x/image to v0.47.0 ([#355](https://github.com/tuna-os/bluefin-cli/issues/355)) ([c859aca](https://github.com/tuna-os/bluefin-cli/commit/c859acaf84abbdbb592e0d62cccfad714b27a3d2))
  • **deps:** update module golang.org/x/sys to v0.49.0 ([#356](https://github.com/tuna-os/bluefin-cli/issues/356)) ([3581390](https://github.com/tuna-os/bluefin-cli/commit/35813906b585128279dee5532e92a7f43683d31b))
ReleaseNotesUrl: https://github.com/tuna-os/bluefin-cli/releases/tag/v0.11.8
ManifestType: defaultLocale
ManifestVersion: 1.12.0
