# Created with komac v2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.6.0.schema.json

PackageIdentifier: ExpressVPN.ExpressVPN
PackageVersion: 12.80.0.11
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.6.0
