# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Maxthon.Maxthon
PackageVersion: 7.3.1.3000
InstallerType: exe
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --slient
  SilentWithProgress: --slient
  InstallLocation: --install-path="<INSTALLPATH>"
  Log: --verbose-logging --log-file="<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 22
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 60
  ReturnResponse: installInProgress
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- mms
- mnt
- mx
- nb
- tel
- tx
FileExtensions:
- htm
- html
- pdf
- rss
- shtml
- svg
- svgz
- url
- webp
- xht
- xhtml
- xsl
ProductCode: Maxthon
ReleaseDate: 2025-02-19
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x86.exe
  InstallerSha256: 57C2E20F4FEECE1FC96362E659BD696395CDFB8B0D9751E0448FBF154235D753
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x86.exe
  InstallerSha256: 57C2E20F4FEECE1FC96362E659BD696395CDFB8B0D9751E0448FBF154235D753
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x64.exe
  InstallerSha256: CF7CE537FF2D5DEE7A6E5D0D1E89A52C0A3FA3EE7A6151A64B2A8BE5E7545B1F
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x64.exe
  InstallerSha256: CF7CE537FF2D5DEE7A6E5D0D1E89A52C0A3FA3EE7A6151A64B2A8BE5E7545B1F
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
- InstallerLocale: zh-CN
  Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x86.exe
  InstallerSha256: 57C2E20F4FEECE1FC96362E659BD696395CDFB8B0D9751E0448FBF154235D753
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- InstallerLocale: zh-CN
  Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x86.exe
  InstallerSha256: 57C2E20F4FEECE1FC96362E659BD696395CDFB8B0D9751E0448FBF154235D753
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x64.exe
  InstallerSha256: CF7CE537FF2D5DEE7A6E5D0D1E89A52C0A3FA3EE7A6151A64B2A8BE5E7545B1F
  InstallerSwitches:
    Custom: --do-not-launch-chrome
- InstallerLocale: zh-CN
  Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/maxthon/update/releases/download/7.3.1.3000/maxthon_7.3.1.3000_beta_x64.exe
  InstallerSha256: CF7CE537FF2D5DEE7A6E5D0D1E89A52C0A3FA3EE7A6151A64B2A8BE5E7545B1F
  InstallerSwitches:
    Custom: --do-not-launch-chrome --system-level
ManifestType: installer
ManifestVersion: 1.9.0
