# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Aries-Sciences-LLC.AI-Chess
PackageVersion: '1.0'
InstallerType: exe
ReleaseDate: 2021-12-07
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/Aries-Sciences-LLC/AI-Chess/releases/download/1.0/AI.Chess.Game.Installer.exe
  InstallerSha256: F6C29F70605CBA36120CF2BF0E3D059832D4C239D702B9997CD18AE60DA79F6A
ManifestType: installer
ManifestVersion: 1.9.0
