# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Altova.MissionKit.2025.Professional
PackageVersion: 2026.00.00.00
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Log: /L* "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 6
  ReturnResponse: installInProgress
UpgradeBehavior: install
FileExtensions:
- altova_licenses
- altova_licenses_server
- altova_xmlschemas
- asp
- avro
- avsc
- biz
- cml
- cpp
- css
- dcd
- dtd
- ent
- epub
- fo
- h
- js
- json
- json5
- jsonc
- jsonl
- jsp
- kml
- kmz
- math
- md
- mfd
- mff
- mfp
- mml
- pptx
- pxf
- py
- qdes
- qprj
- rdf
- smil
- spp
- sps
- sql
- svp
- tld
- txt
- ump
- vml
- vxml
- wml
- wsdl
- x3d
- xbr
- xbri
- xbrl
- xdr
- xhtml
- xlsx
- xml
- xq
- xql
- xqr
- xqu
- xquery
- xsd
- xsig
- xsl
- xslt
- xule
- yaml
- yml
- zip
ReleaseDate: 2025-10-20
AppsAndFeaturesEntries:
- InstallerType: msi
Installers:
- InstallerLocale: ja
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026.exe
  InstallerSha256: 8AF70A618703E3134BA3C4960F6A738DE93F8195B955B754CC247042EC8DCF65
  ProductCode: '{F1375824-F7D3-43F1-98FD-5CBE3D859095}'
- InstallerLocale: ja
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026_x64.exe
  InstallerSha256: CC4059BC64ED5EE134353C58B671148923A5284BF0C97B266B6501C09586960F
  ProductCode: '{0D164A7C-BFB9-4077-8F4B-ABE42EDA8D1D}'
- InstallerLocale: fr
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026.exe
  InstallerSha256: 8AF70A618703E3134BA3C4960F6A738DE93F8195B955B754CC247042EC8DCF65
  ProductCode: '{F1375824-F7D3-43F1-98FD-5CBE3D859095}'
- InstallerLocale: fr
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026_x64.exe
  InstallerSha256: CC4059BC64ED5EE134353C58B671148923A5284BF0C97B266B6501C09586960F
  ProductCode: '{0D164A7C-BFB9-4077-8F4B-ABE42EDA8D1D}'
- InstallerLocale: es
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026.exe
  InstallerSha256: 8AF70A618703E3134BA3C4960F6A738DE93F8195B955B754CC247042EC8DCF65
  ProductCode: '{F1375824-F7D3-43F1-98FD-5CBE3D859095}'
- InstallerLocale: es
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026_x64.exe
  InstallerSha256: CC4059BC64ED5EE134353C58B671148923A5284BF0C97B266B6501C09586960F
  ProductCode: '{0D164A7C-BFB9-4077-8F4B-ABE42EDA8D1D}'
- InstallerLocale: en
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026.exe
  InstallerSha256: 8AF70A618703E3134BA3C4960F6A738DE93F8195B955B754CC247042EC8DCF65
  ProductCode: '{F1375824-F7D3-43F1-98FD-5CBE3D859095}'
- InstallerLocale: en
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026_x64.exe
  InstallerSha256: CC4059BC64ED5EE134353C58B671148923A5284BF0C97B266B6501C09586960F
  ProductCode: '{0D164A7C-BFB9-4077-8F4B-ABE42EDA8D1D}'
- InstallerLocale: de
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026.exe
  InstallerSha256: 8AF70A618703E3134BA3C4960F6A738DE93F8195B955B754CC247042EC8DCF65
  ProductCode: '{F1375824-F7D3-43F1-98FD-5CBE3D859095}'
- InstallerLocale: de
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitProf2026_x64.exe
  InstallerSha256: CC4059BC64ED5EE134353C58B671148923A5284BF0C97B266B6501C09586960F
  ProductCode: '{0D164A7C-BFB9-4077-8F4B-ABE42EDA8D1D}'
ManifestType: installer
ManifestVersion: 1.10.0
