# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Gawindx.WinNUT
PackageVersion: 2.0.7722.30975
InstallerLocale: und
InstallerType: msi
Scope: user
ProductCode: '{27BA937E-88CF-46BD-9BDA-2426BDE4BA49}'
ReleaseDate: 2021-12-07
AppsAndFeaturesEntries:
- DisplayVersion: 2.0.7722
  ProductCode: '{27BA937E-88CF-46BD-9BDA-2426BDE4BA49}'
  UpgradeCode: '{7EA17151-76E7-4E29-8F6A-621C1B4144C2}'
InstallationMetadata: {}
Installers:
- Architecture: neutral
  InstallerUrl: https://github.com/gawindx/WinNUT-Client/releases/download/v2.0.7722.30975/WinNUT-Setup.msi
  InstallerSha256: AFE7BB9F696ACA17FC2C4BF16DCFD4A70221F8114D987ACF71D51D1C4F3EEF4C
ManifestType: installer
ManifestVersion: 1.9.0
