# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: AbdelrahmanBayoumi.Azkar
PackageVersion: 1.2.9
PackageLocale: en-US
Publisher: Abdelrahman Bayoumi
PublisherUrl: https://github.com/AbdelrahmanBayoumi
PublisherSupportUrl: https://github.com/AbdelrahmanBayoumi/Azkar-App/issues
Author: Abdelrahman Bayoumi
PackageName: Azkar
PackageUrl: https://azkar-site.web.app/
License: MIT
LicenseUrl: https://github.com/AbdelrahmanBayoumi/Azkar-App/blob/HEAD/LICENSE
Copyright: Copyright (c) 2020 Abdelrahman Bayoumi
CopyrightUrl: https://raw.githubusercontent.com/AbdelrahmanBayoumi/Azkar-App/master/LICENSE
ShortDescription: Desktop Application for Calculating Muslim prayer times, Morning and Nights Azkar with notification for random Azkar that pops-up in specific time.
Description: Desktop Application for Calculating Muslim prayer times, Morning and Nights Azkar with notification for random Azkar that pops-up in specific time.
Moniker: azkar
Tags:
- prayer-times
ReleaseNotes: |-
  Fix
  - Bundle EXE with 1.8_271 not 1.8_221
  - Fix Timed Azkar window delay
  - Exception: Error in getCityFromCoordinates() && getCityFromEngName() #43
  - Fix NullPointerException #42
  Full Changelog: 1.2.6...1.2.7
ReleaseNotesUrl: https://github.com/AbdelrahmanBayoumi/Azkar-App/releases/tag/1.2.7
ManifestType: defaultLocale
ManifestVersion: 1.9.0
