# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AbdelrahmanBayoumi.Azkar
PackageVersion: 1.2.9
InstallerLocale: ar-SA
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -q
  SilentWithProgress: -q
UpgradeBehavior: install
ReleaseDate: 2023-07-17
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/AbdelrahmanBayoumi/Azkar-App/releases/download/1.2.7/Azkar_windows-x32.exe
  InstallerSha256: AF0999770A981117BA4D2903E15D135AD9BAFFFF8DD88F619D5267EB19D231DC
ManifestType: installer
ManifestVersion: 1.9.0
