# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: JetBrains.GoLand
PackageVersion: 2023.3.4
InstallerType: nullsoft
InstallerSwitches:
  Log: /LOG="<LOGPATH>"
UpgradeBehavior: uninstallPrevious
FileExtensions:
- go
- ipr
AppsAndFeaturesEntries:
- DisplayName: GoLand 2023.3.4
  DisplayVersion: 233.14475.38
  ProductCode: GoLand 2023.3.4
Installers:
- Architecture: x64
  InstallerUrl: https://download-cdn.jetbrains.com/go/goland-2023.3.4.exe
  InstallerSha256: 2E779C6178AFEBEDA467EC7C1634BCE8B6AF6F919D3929B1ECD282DBD56E3A89
  ProductCode: GoLand 2023.3.4
- Architecture: arm64
  InstallerUrl: https://download-cdn.jetbrains.com/go/goland-2023.3.4-aarch64.exe
  InstallerSha256: 21869085A53CA5C13534C813AA25BED30FD9DBEDE5A1BDF7916E67D369A21DD6
  ProductCode: GoLand 2023.3.4
ManifestType: installer
ManifestVersion: 1.5.0
