# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: JetBrains.TeamCity
PackageVersion: 2023.11.2
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ProductCode: JetBrains TeamCity
AppsAndFeaturesEntries:
- DisplayVersion: Build 147412
  ProductCode: JetBrains TeamCity
Installers:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/teamcity/TeamCity-2023.11.2.exe
  InstallerSha256: B9708ECC6E03802328614992D6938D29F0864C22E407D9BF6613972CF52494D3
ManifestType: installer
ManifestVersion: 1.5.0
