# Created using wingetcreate 1.5.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Iterate.Cyberduck
PackageVersion: 8.7.1.40770
InstallerLocale: en-US
Platform:
- Windows.Desktop
Scope: machine
Installers:
- Architecture: x64
  InstallerType: burn
  InstallerUrl: https://update.cyberduck.io//Cyberduck-Installer-8.7.1.40770.exe
  InstallerSha256: 1A41FFAF497CC1692B60B90DC9D323F7098DC5DB6A0F512817FC9A072F4F20F7
  ProductCode: '{04524BC9-43C8-4523-A0BC-36E0BAAEDEA8}'
- Architecture: x64
  InstallerType: msi
  InstallerUrl: https://update.cyberduck.io//Cyberduck-Installer-8.7.1.40770.msi
  InstallerSha256: B0E5EA8A877E47831F5F501F089BE783D0CEBE41D4C73E902C061A5648C84F6D
  ProductCode: '{2E3987C4-DDF1-4DF7-A3ED-AD9D84D22E98}'
  AppsAndFeaturesEntries:
  - UpgradeCode: '{B9C33495-4B77-4863-9A40-4E767388647E}'
ManifestType: installer
ManifestVersion: 1.5.0
