# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: BiglySoftware.BiglyBT
PackageVersion: 3.7.0.0
Platform:
- Windows.Desktop
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: -q
  InstallLocation: -dir "<INSTALLPATH>"
  Log: -Dinstall4j.log="<LOGPATH>"
UpgradeBehavior: install
Protocols:
- magnet
FileExtensions:
- torrent
ProductCode: 0112-2557-8304-7048
ReleaseDate: 2024-09-30
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/BiglySoftware/BiglyBT/releases/download/v3.7.0.0/GitHub_BiglyBT_Installer32.exe
  InstallerSha256: EABCAA2BEA6BAF879CDE6B54C1ED342A46881E2A904ECE1025960926C52D948F
ManifestType: installer
ManifestVersion: 1.9.0
