# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Microsoft.Skype
PackageVersion: 8.113.0.210
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Skype_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://download.skype.com/s4l/download/win/Skype-8.113.0.210.exe
  InstallerSha256: 42C40001E88F0DB82B6AFFC4CA9F9F1C0440A6DA3F502F9F67C7BB81D315F08F
ManifestType: installer
ManifestVersion: 1.6.0
