# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Opera.OperaGX
PackageVersion: 111.0.5168.99
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- opera-gxstable
FileExtensions:
- crx
- gxanimations
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://ftp.opera.com/ftp/pub/opera_gx/111.0.5168.99/win/Opera_GX_111.0.5168.99_Setup.exe
  InstallerSha256: 78A1E6C0106F5FDCB0F867ABF173FCAED72863C6A9D7694E551309738CAA273A
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://ftp.opera.com/ftp/pub/opera_gx/111.0.5168.99/win/Opera_GX_111.0.5168.99_Setup.exe
  InstallerSha256: 78A1E6C0106F5FDCB0F867ABF173FCAED72863C6A9D7694E551309738CAA273A
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://ftp.opera.com/ftp/pub/opera_gx/111.0.5168.99/win/Opera_GX_111.0.5168.99_Setup_x64.exe
  InstallerSha256: 99BC9C94C52380649A605ED224CC617D1BF7D346A525F64979A0C96208FBE4C4
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://ftp.opera.com/ftp/pub/opera_gx/111.0.5168.99/win/Opera_GX_111.0.5168.99_Setup_x64.exe
  InstallerSha256: 99BC9C94C52380649A605ED224CC617D1BF7D346A525F64979A0C96208FBE4C4
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.6.0
