# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.AzureMediaServicesExplorer
PackageVersion: 5.8.3.0
InstallerLocale: en-US
InstallerType: msi
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.7
  - PackageIdentifier: Microsoft.EdgeWebView2Runtime
ProductCode: '{08CB3739-9C90-4F41-B3F2-A44DA8228ACE}'
ReleaseDate: 2024-06-14
AppsAndFeaturesEntries:
- Publisher: Microsoft Corporation
  ProductCode: '{08CB3739-9C90-4F41-B3F2-A44DA8228ACE}'
  UpgradeCode: '{5145C7B3-B64F-42CA-A111-45E636E02027}'
InstallationMetadata: {}
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Azure/Azure-Media-Services-Explorer/releases/download/v5.8.3.0/AMSExplorerSetup_v5.8.3.msi
  InstallerSha256: 9C0C5AE2D7C2F070C4DAE65259BD1624C16EFD934BE51293B6B50EE220F29EE5
ManifestType: installer
ManifestVersion: 1.9.0
