# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Fortinet.FortiClientVPN
PackageVersion: 7.2.11.1241
PackageLocale: en-US
Publisher: Fortinet Technologies Inc
PackageName: FortiClient VPN
License: Proprietary
ShortDescription: Free VPN client for FortiClient
Moniker: forticlientvpn
ManifestType: defaultLocale
ManifestVersion: 1.10.0
