# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Opera.Opera
PackageVersion: 111.0.5168.55
InstallerType: exe
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- ftp
- http
- https
- mailto
- operastable
FileExtensions:
- crx
- htm
- html
- opdownload
- pdf
- shtml
- xht
- xhtml
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/111.0.5168.55/win/Opera_111.0.5168.55_Setup.exe
  InstallerSha256: EE41D1ED06BB0B5EA272F7D76E576F59F206BCB151D7556DA6471C96CF276F91
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x86
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/111.0.5168.55/win/Opera_111.0.5168.55_Setup.exe
  InstallerSha256: EE41D1ED06BB0B5EA272F7D76E576F59F206BCB151D7556DA6471C96CF276F91
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: x64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/111.0.5168.55/win/Opera_111.0.5168.55_Setup_x64.exe
  InstallerSha256: B40DCB1442ED6C422C51F1AC9173DB559DC2849DDB8303B439687B8D49D2AFF0
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: x64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/111.0.5168.55/win/Opera_111.0.5168.55_Setup_x64.exe
  InstallerSha256: B40DCB1442ED6C422C51F1AC9173DB559DC2849DDB8303B439687B8D49D2AFF0
  InstallerSwitches:
    Custom: /allusers=1
- Architecture: arm64
  Scope: user
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/111.0.5168.55/win/Opera_111.0.5168.55_Setup_arm64.exe
  InstallerSha256: 821BBDFAA7D9C0DA35C37DCFFC12DE81ECFA8FD934369800CB6BC96081A7B816
  InstallerSwitches:
    Custom: /allusers=0
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://get.geo.opera.com/pub/opera/desktop/111.0.5168.55/win/Opera_111.0.5168.55_Setup_arm64.exe
  InstallerSha256: 821BBDFAA7D9C0DA35C37DCFFC12DE81ECFA8FD934369800CB6BC96081A7B816
  InstallerSwitches:
    Custom: /allusers=1
ManifestType: installer
ManifestVersion: 1.6.0
