# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: geeksoftwareGmbH.PDF24Creator
PackageVersion: 11.31.1
InstallerLocale: en-US
Scope: machine
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerType: wix
  InstallerUrl: https://download.pdf24.org/pdf24-creator-11.31.1-x64.msi
  InstallerSha256: 54EC270661EF304AE83A5E882235F66A258B9202535B4CA5E978A8D8CAFC2086
  ProductCode: '{EFED6366-5D56-4187-A772-C1C3E458B455}'
- Architecture: x64
  InstallerType: inno
  InstallerUrl: https://download.pdf24.org/pdf24-creator-11.31.1-x64.exe
  InstallerSha256: 4D82B437DE70E273A8DA55E9268830A0588209D2016A3E8A11552C081740DCD4
  InstallerSwitches:
    Custom: /NOUPDATE /NORESTART
  AppsAndFeaturesEntries:
  - Publisher: PDF24.org
    ProductCode: '{81A6F461-0DBA-4F12-B56F-0E977EC10576}_is1'
- Architecture: x86
  InstallerType: wix
  InstallerUrl: https://download.pdf24.org/pdf24-creator-11.31.1-x86.msi
  InstallerSha256: 3A6BF271A282F92CE7D2430C74A858A9BC0CBE212A5683A263DF964927EE9625
  ProductCode: '{B9D159E7-25A0-4989-9B39-6F23A5E654F2}'
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://download.pdf24.org/pdf24-creator-11.31.1-x86.exe
  InstallerSha256: 5C02A7F77005FBB14F78C3AC15774E1BBAB8897DD4A82EF3447D825899715B79
  InstallerSwitches:
    Custom: /NOUPDATE /NORESTART
  AppsAndFeaturesEntries:
  - Publisher: PDF24.org
    ProductCode: '{81A6F461-0DBA-4F12-B56F-0E977EC10576}_is1'
- Architecture: arm64
  InstallerType: wix
  InstallerUrl: https://download.pdf24.org/pdf24-creator-11.31.1-arm64.msi
  InstallerSha256: 70B784E85664BC3728BFA33831B66CB6D78FF0EFC4729A8D4ED1EFECC542A9E7
  ProductCode: '{4BC31427-7435-4E90-A2CC-7DC653637F98}'
- Architecture: arm64
  InstallerType: inno
  InstallerUrl: https://download.pdf24.org/pdf24-creator-11.31.1-arm64.exe
  InstallerSha256: A249887F6C3BE2A0EEDCE8C0C7816A2D437E05135527652926C7211825FB0B1C
  InstallerSwitches:
    Custom: /NOUPDATE /NORESTART
  AppsAndFeaturesEntries:
  - Publisher: PDF24.org
    ProductCode: '{81A6F461-0DBA-4F12-B56F-0E977EC10576}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
