# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Zoom.Zoom.VDI
PackageVersion: 6.5.26710
PackageLocale: en-US
Publisher: Zoom Video Communications, Inc.
PublisherUrl: https://zoom.us/
PublisherSupportUrl: https://support.zoom.us/
PrivacyUrl: https://explore.zoom.us/en/privacy/
Author: Zoom Video Communications, Inc.
PackageName: Zoom VDI Workplace
PackageUrl: https://zoom.us/
License: Proprietary
LicenseUrl: https://explore.zoom.us/en/terms/
Copyright: Copyright ©2012-2024 Zoom Video Communications, Inc. All rights reserved.
ShortDescription: Zoom Client for VDI
Tags:
- chat
- collaborate
- collaboration
- conference
- conferencing
- meeting
- video-conferencing
- voice-conferencing
- webinar
PurchaseUrl: https://zoom.us/pricing
Documentations:
- DocumentLabel: Learning Center
  DocumentUrl: https://learning.zoom.us/learn
ManifestType: defaultLocale
ManifestVersion: 1.10.0
