# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Zoom.Zoom.VDI
PackageVersion: 6.5.26710
InstallerLocale: en-US
InstallerType: msi
Scope: machine
UpgradeBehavior: install
Protocols:
- zoom
- zoommtg
FileExtensions:
- zoommtg
- zoomphonecall
ProductCode: '{F92A6BD0-9AC8-47BC-B5F1-570F8BAF4E1A}'
ReleaseDate: 2025-09-05
AppsAndFeaturesEntries:
- DisplayName: Zoom VDI Workplace (64-bit)
  Publisher: Zoom Communications, Inc.
  ProductCode: '{F92A6BD0-9AC8-47BC-B5F1-570F8BAF4E1A}'
  UpgradeCode: '{03AAFC2F-FBD3-4B2D-9364-2FF6D39D939A}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\ZoomVDI'
Installers:
- Architecture: x64
  InstallerUrl: https://zoom.us/download/vdi/6.5.10.26710/ZoomInstallerVDI.msi?archType=x64
  InstallerSha256: 2591524E20C45E373A44728D3C21D7E13D3F84BC611926826D981CD955B401F2
ManifestType: installer
ManifestVersion: 1.10.0
