# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Devolutions.RemoteDesktopManager
PackageVersion: 2026.3.13.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
Protocols:
- rdp
FileExtensions:
- csv
- psafe3
- rde
- rdg
- rdm
- rdp
- vnc
- vrb
- vrd
- vre
- xml
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.10
ProductCode: '{D95A8F88-AD21-4E4A-807E-BD5B5901717B}'
AppsAndFeaturesEntries:
- UpgradeCode: '{2707F3BF-4D7B-40C2-882F-14B0ED869EE8}'
Installers:
- Architecture: neutral
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.2026.3.13.0.msi
  InstallerSha256: B68271C405AFCB58CE8F80B66D01D2C9472E33E18457B28D05728CB641C1B94D
- Architecture: x64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.win-x64.2026.3.13.0.msi
  InstallerSha256: 7490E10C23264C554A0C10A954A1958E77C98C2C6F98745300B35B70B24B690C
- Architecture: arm64
  InstallerUrl: https://cdn.devolutions.net/download/Setup.RemoteDesktopManager.win-arm64.2026.3.13.0.msi
  InstallerSha256: 3DCC2BC558FA7EA0412EBD8070D7F3E58E4E518590F0A208AB6986FD42EA67EA
ManifestType: installer
ManifestVersion: 1.12.0
