# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: CondaForge.Miniforge3
PackageVersion: 24.11.3
PackageLocale: en-US
Publisher: conda-forge
PublisherUrl: https://conda-forge.org/
PublisherSupportUrl: https://github.com/conda-forge/miniforge/issues
Author: conda-forge
PackageName: Miniforge3
PackageUrl: https://github.com/conda-forge/miniforge
License: BSD-3-Clause
LicenseUrl: https://github.com/conda-forge/miniforge/blob/HEAD/LICENSE
Copyright: Copyright (c) 2019-2024, conda-forge
ShortDescription: Miniforge is a free minimal installer for conda specific to conda-forge.
Moniker: miniforge3
Tags:
- anaconda
- conda
- conda-forge
- mamba
- python
ReleaseNotes: |-
  What's Changed
  - Improve readme by @paugier in #686
  - Remove miniforge name customization by @hmaarrfk in #711
  - Update to 24.11.3 by @hmaarrfk in #713
  New Contributors
  - @paugier made their first contribution in #686
  Full Changelog: 24.11.2-1...24.11.3-0
ReleaseNotesUrl: https://github.com/conda-forge/miniforge/releases/tag/24.11.3-0
Documentations:
- DocumentLabel: Docs
  DocumentUrl: https://conda-forge.org/docs/
ManifestType: defaultLocale
ManifestVersion: 1.9.0
