# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Headlamp.Headlamp
PackageVersion: 0.27.0
PackageLocale: en-US
Publisher: Headlamp
PublisherUrl: https://headlamp.dev
PublisherSupportUrl: https://github.com/headlamp-k8s/headlamp/issues
PackageName: Headlamp
PackageUrl: https://github.com/headlamp-k8s/headlamp
License: Apache 2.0
LicenseUrl: https://github.com/headlamp-k8s/headlamp/blob/main/LICENSE
ShortDescription: Kubernetes web UI.
Description: A Kubernetes web UI that is fully-featured, user-friendly and extensible.
Tags:
- kubernetes
- plugins
- kinvolk
- headlamp
- dashboard
- ui
- web
- monitoring
- logging
- cncf
ReleaseNotesUrl: https://github.com/headlamp-k8s/headlamp/releases/tag/v0.27.0
Documentations:
- DocumentLabel: headlamp documentation
  DocumentUrl: https://headlamp.dev/docs/latest
ManifestType: defaultLocale
ManifestVersion: 1.9.0
