# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ChidiWilliams.Buzz
PackageVersion: 1.2.0
InstallerLocale: en-US
InstallerType: inno
ProductCode: '{574290A2-EF7C-4845-85F3-BFF2F011A580}_is1'
ReleaseDate: 2024-12-20
AppsAndFeaturesEntries:
- ProductCode: '{574290A2-EF7C-4845-85F3-BFF2F011A580}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/chidiwilliams/buzz/releases/download/v1.2.0/Buzz-1.2.0-windows.exe
  InstallerSha256: BBC37EB36C517D3E9F25D5D247728A2684F355AE8702DCAC85C45E7F332B8244
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/chidiwilliams/buzz/releases/download/v1.2.0/Buzz-1.2.0-windows.exe
  InstallerSha256: BBC37EB36C517D3E9F25D5D247728A2684F355AE8702DCAC85C45E7F332B8244
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Buzz'
ManifestType: installer
ManifestVersion: 1.9.0
