# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Zoom.Zoom
PackageVersion: 5.17.1.28914
InstallerLocale: en-US
UpgradeBehavior: install
Protocols:
- zoom
- zoommtg
FileExtensions:
- zoommtg
- zoomphonecall
Installers:
- Architecture: x86
  InstallerType: exe
  Scope: user
  InstallerUrl: https://cdn.zoom.us/prod/5.17.1.28914/ZoomInstallerFull.exe
  InstallerSha256: EE3A8122F64FFDE5421C2C8691329DE7FC464C44E997CF695C73D4582AC1C43D
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - DisplayName: Zoom(32bit)
    Publisher: Zoom Video Communications, Inc.
    DisplayVersion: 5.17.1 (28914)
    ProductCode: ZoomUMX
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://cdn.zoom.us/prod/5.17.1.28914/x64/ZoomInstallerFull.exe
  InstallerSha256: EE3A8122F64FFDE5421C2C8691329DE7FC464C44E997CF695C73D4582AC1C43D
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - DisplayVersion: 5.17.1 (28914)
    ProductCode: ZoomUMX
- Architecture: arm64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://cdn.zoom.us/prod/5.17.1.28914/arm64/ZoomInstallerFull.exe
  InstallerSha256: EE3A8122F64FFDE5421C2C8691329DE7FC464C44E997CF695C73D4582AC1C43D
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /silent
    SilentWithProgress: /silent
  ProductCode: ZoomUMX
  AppsAndFeaturesEntries:
  - DisplayVersion: 5.17.1 (28914)
    ProductCode: ZoomUMX
- Architecture: x86
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://cdn.zoom.us/prod/5.17.1.28914/ZoomInstallerFull.msi
  InstallerSha256: 3B5B1403CC9C25C53B42CBC3D16138BF2959AAFF27C1491D6DF27EFBD10451E3
  ProductCode: '{0141B9DE-5A20-430D-BF94-B87B61994755}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (32-bit)
    DisplayVersion: 5.17.1 (28914)
    ProductCode: '{0141B9DE-5A20-430D-BF94-B87B61994755}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
- Architecture: x64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://cdn.zoom.us/prod/5.17.1.28914/x64/ZoomInstallerFull.msi
  InstallerSha256: 3B5B1403CC9C25C53B42CBC3D16138BF2959AAFF27C1491D6DF27EFBD10451E3
  ProductCode: '{0141B9DE-5A20-430D-BF94-B87B61994755}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (64-bit)
    DisplayVersion: 5.17.1 (28914)
    ProductCode: '{0141B9DE-5A20-430D-BF94-B87B61994755}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
- Architecture: arm64
  InstallerType: msi
  Scope: machine
  InstallerUrl: https://cdn.zoom.us/prod/5.17.1.28914/arm64/ZoomInstallerFull.msi
  InstallerSha256: 3B5B1403CC9C25C53B42CBC3D16138BF2959AAFF27C1491D6DF27EFBD10451E3
  ProductCode: '{0141B9DE-5A20-430D-BF94-B87B61994755}'
  AppsAndFeaturesEntries:
  - DisplayName: Zoom (ARM64)
    DisplayVersion: 5.17.1 (28914)
    ProductCode: '{0141B9DE-5A20-430D-BF94-B87B61994755}'
    UpgradeCode: '{C819B794-A45C-4F27-9860-0C86492A52CC}'
ManifestType: installer
ManifestVersion: 1.5.0
