# Created with komac v2.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.Sysinternals.Sysmon
PackageVersion: 15.15.0
InstallerType: portable
Commands:
- Sysmon
ReleaseDate: 2024-07-23
Installers:
- Architecture: arm64
  InstallerUrl: https://live.sysinternals.com/ARM64/Sysmon64a.exe
  InstallerSha256: A8E55C8530236CAABD5126D45BD8BD9EC6B266E387C5CCD436C23F4ECEA386B3
- Architecture: neutral
  InstallerUrl: https://live.sysinternals.com/Sysmon.exe
  InstallerSha256: 16E4ED3EA1D4C67213799905D61A2722CF08A0B74A885E58B743B91D3CDDFC87
ManifestType: installer
ManifestVersion: 1.9.0
