# Automatically updated by the winget bot at 2026/Oct/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Tencent.WorkBuddy
PackageVersion: 5.5.3
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: BFD312E9-1019-4F57-9F44-F86246833B50
ReleaseDate: 2026-09-03
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.5.3.37748631-104760a2.exe
  InstallerSha256: E2B0216C673446682F32238F9074FB62D9031E5AC83344CB363EF83C561668B0
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.5.3.37748631-104760a2.exe
  InstallerSha256: E2B0216C673446682F32238F9074FB62D9031E5AC83344CB363EF83C561668B0
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.28.0
