# Created with komac v2.10.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: Mersive.MersiveSolstice
PackageVersion: 6.2.37754
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
