# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: albertony.npiperelay
PackageVersion: 1.8.0
InstallerType: zip
NestedInstallerType: portable
ReleaseDate: 2025-02-13
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/albertony/npiperelay/releases/download/v1.8.0/npiperelay_windows_386.exe
  InstallerSha256: 730780838D807D9A0E121E7E77BBA2658C140C2276578D28F9608B3FBEF6D0C5
ManifestType: installer
ManifestVersion: 1.9.0
