# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Axosoft.GitKraken
PackageVersion: 10.1.0
InstallerType: exe
Scope: user
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: --silent
  SilentWithProgress: --silent
UpgradeBehavior: install
Protocols:
- gitkraken
ProductCode: gitkraken
Installers:
- Architecture: x64
  InstallerUrl: https://release.axocdn.com/windows/GitKrakenSetup.exe
  InstallerSha256: AF986F83AE19C5C838B41F383C35D328BF8DD28501E3E63E9864038BE23CF4D9
ManifestType: installer
ManifestVersion: 1.6.0
