# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: JetBrains.TeamCity
PackageVersion: 2023.11.4
PackageLocale: en-US
Publisher: JetBrains s.r.o.
PublisherUrl: https://www.jetbrains.com/
PublisherSupportUrl: https://www.jetbrains.com/support/
PrivacyUrl: https://www.jetbrains.com/legal/docs/privacy/privacy/
Author: JetBrains s.r.o.
PackageName: JetBrains TeamCity
PackageUrl: https://www.jetbrains.com/teamcity/
License: Proprietary
LicenseUrl: https://www.jetbrains.com/legal/docs/toolbox/user/
Copyright: Copyright © 2000-2024 JetBrains s.r.o.
ShortDescription: Powerful continuous integration for DevOps-centric teams
Description: The powerful Continuous Integration and Deployment tool for Developers and DevOps Engineers.
Moniker: teamcity
Tags:
- cd
- ci
- develop
- development
- devops
PurchaseUrl: https://www.jetbrains.com/teamcity/buy/
Documentations:
- DocumentLabel: Learn TeamCity
  DocumentUrl: https://www.jetbrains.com/teamcity/learn/
ManifestType: defaultLocale
ManifestVersion: 1.6.0
