# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: JetBrains.TeamCity
PackageVersion: 2023.11.4
InstallerType: nullsoft
Scope: machine
UpgradeBehavior: install
ProductCode: JetBrains TeamCity
AppsAndFeaturesEntries:
- DisplayVersion: Build 147512
  ProductCode: JetBrains TeamCity
Installers:
- Architecture: x64
  InstallerUrl: https://download.jetbrains.com/teamcity/TeamCity-2023.11.4.exe
  InstallerSha256: 4C371054BA0940628A411D8957CC76B5BD5C6A68F4B568E5060BA9BDA00AA23F
ManifestType: installer
ManifestVersion: 1.6.0
