# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.70.3
Scope: machine
UpgradeBehavior: install
Protocols:
- blizzv1
- teamviewer10
- teamviewer8
- teamviewerapi
- tvchat1
- tvcontrol1
- tvfiletransfer1
- tvjoinv8
- tvoneweblogin
- tvpresent1
- tvsendfile1
- tvsqcustomer1
- tvsqsupport1
- tvvideocall1
- tvvpn1
FileExtensions:
- tpsr
- tvc
- tvlink
- tvs
ReleaseDate: 2025-10-01
Installers:
- Architecture: neutral
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Full/TeamViewer_Full.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: E558FF8094D4087AE835BFD27C288E1639796F2CF2939BDD44DF3E620C0874B0
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{63973253-4216-4B69-99B8-E8B28611520B}'
  AppsAndFeaturesEntries:
  - ProductCode: '{63973253-4216-4B69-99B8-E8B28611520B}'
    UpgradeCode: '{F0C19578-BC20-4F79-B2C3-EA824DE91F34}'
- Architecture: neutral
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Full/TeamViewer_Full.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: E558FF8094D4087AE835BFD27C288E1639796F2CF2939BDD44DF3E620C0874B0
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{CA124E5C-9D05-4298-B1BA-D8A3FEDF08C7}'
  AppsAndFeaturesEntries:
  - ProductCode: '{CA124E5C-9D05-4298-B1BA-D8A3FEDF08C7}'
    UpgradeCode: '{98A72954-BC0F-11E8-9CC6-3F794D8C2BDE}'
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup.exe
  InstallerSha256: 03DAD90A9A84AF15D6850D0AC075E46FEC1F5043DC14FFF7F9E4D521FD3E93B2
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
  InstallerSha256: 87F41DFBDE74B55B2334F5A398A192A23B9E05E1DB92E7B8192A88922CDEF485
ManifestType: installer
ManifestVersion: 1.10.0
