# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: evernote.evernote
PackageVersion: 10.70.2
Platform:
- Windows.Desktop
InstallerType: nullsoft
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: 34D5319F22BD91D33E94316268E626512F373D47AFAA19E751F373583CBB4F70
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://win.desktop.evernote.com/builds/Evernote-latest.exe
  InstallerSha256: 34D5319F22BD91D33E94316268E626512F373D47AFAA19E751F373583CBB4F70
  InstallerSwitches:
    Custom: /ALLUSERS
ManifestType: installer
ManifestVersion: 1.5.0
