# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: DanielMcGuireCorporation.SimpleBrowser
PackageVersion: 2.5.1.2
PackageLocale: en-US
Publisher: Daniel McGuire Corporation
PublisherUrl: https://github.com/Daniel-McGuire-Corporation
PublisherSupportUrl: https://github.com/Daniel-McGuire-Corporation/Simple-BrowserCS/issues
PackageName: Simple Browser
PackageUrl: https://github.com/Daniel-McGuire-Corporation/Simple-BrowserCS
License: MIT
LicenseUrl: https://github.com/Daniel-McGuire-Corporation/Simple-BrowserCS/blob/HEAD/LICENSE
Copyright: Daniel McGuire Corporation
ShortDescription: Simple Web Browser
Tags:
- browser
- chromium
- csharp
- good-first-issue
- open-source
- webbrowsing
ReleaseNotes: |-
  Learn More about how we make our version string!
  What's Changed
  - Versioning system fixed
  - Fixed an issue where SB opens to File not found (#9)
  - SB Legacy added (Read More)
  - Full Changelog: v2.5.0.0...v2.5.1.2
  Check this release on VirusTotal
  Checksums
  - SimpleBrowserSetup.exe SHA256:
  77F3272D6B41DC39C3DBE791682BF2D52DB0AB90AF9701399B4AA35287389D24
  How to Install:
  - WinGet (Available 1 - 2 Hours After Release) (May be delayed if released at night or on non-business days)
    - Run the following command in Powershell / CMD
      winget install DanielMcGuireCorporation.SimpleBrowser
  - Install manually:
    - Download and install dependencies:
      - Browser Runtime Download
      - .NET Desktop Runtime x86-64(64-bit)
  - Install SimpleBrowserSetup.exe below:
ReleaseNotesUrl: https://github.com/Daniel-McGuire-Corporation/Simple-BrowserCS/releases/tag/v2.5.1.2
ManifestType: defaultLocale
ManifestVersion: 1.9.0
