# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Altova.MissionKit.2025.Enterprise
PackageVersion: 2026.00.00.00
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Log: /L* "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 6
  ReturnResponse: installInProgress
UpgradeBehavior: install
FileExtensions:
- altova_licenses
- altova_licenses_server
- altova_xmlschemas
- asp
- avro
- avsc
- biz
- cml
- cpp
- css
- dcd
- dtd
- ent
- epub
- fo
- h
- js
- json
- json5
- jsonc
- jsonl
- jsp
- kml
- kmz
- math
- md
- mfd
- mff
- mfp
- mml
- pptx
- pxf
- py
- qdes
- qprj
- rdf
- smil
- spp
- sps
- sql
- svp
- tld
- txt
- ump
- vml
- vxml
- wml
- wsdl
- x3d
- xbr
- xbri
- xbrl
- xdr
- xhtml
- xlsx
- xml
- xq
- xql
- xqr
- xqu
- xquery
- xsd
- xsig
- xsl
- xslt
- xule
- yaml
- yml
- zip
ReleaseDate: 2025-10-20
AppsAndFeaturesEntries:
- InstallerType: msi
Installers:
- InstallerLocale: ja
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026.exe
  InstallerSha256: 01CD6CA43CAAFABC9D20EBC37D61920547C94549898BED8F825B8D78FA475FF6
  ProductCode: '{3BD2CA68-013A-40D0-B425-0F1DB18A0B3A}'
- InstallerLocale: ja
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026_x64.exe
  InstallerSha256: EF816BA7866CA601FFE0FCEE95B5D7699BD5E5F183D1D2550ACBEAD49BA8E538
  ProductCode: '{3039641E-0317-42AE-98E3-4101D4568452}'
- InstallerLocale: fr
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026.exe
  InstallerSha256: 01CD6CA43CAAFABC9D20EBC37D61920547C94549898BED8F825B8D78FA475FF6
  ProductCode: '{3BD2CA68-013A-40D0-B425-0F1DB18A0B3A}'
- InstallerLocale: fr
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026_x64.exe
  InstallerSha256: EF816BA7866CA601FFE0FCEE95B5D7699BD5E5F183D1D2550ACBEAD49BA8E538
  ProductCode: '{3039641E-0317-42AE-98E3-4101D4568452}'
- InstallerLocale: es
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026.exe
  InstallerSha256: 01CD6CA43CAAFABC9D20EBC37D61920547C94549898BED8F825B8D78FA475FF6
  ProductCode: '{3BD2CA68-013A-40D0-B425-0F1DB18A0B3A}'
- InstallerLocale: es
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026_x64.exe
  InstallerSha256: EF816BA7866CA601FFE0FCEE95B5D7699BD5E5F183D1D2550ACBEAD49BA8E538
  ProductCode: '{3039641E-0317-42AE-98E3-4101D4568452}'
- InstallerLocale: en
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026.exe
  InstallerSha256: 01CD6CA43CAAFABC9D20EBC37D61920547C94549898BED8F825B8D78FA475FF6
  ProductCode: '{3BD2CA68-013A-40D0-B425-0F1DB18A0B3A}'
- InstallerLocale: en
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026_x64.exe
  InstallerSha256: EF816BA7866CA601FFE0FCEE95B5D7699BD5E5F183D1D2550ACBEAD49BA8E538
  ProductCode: '{3039641E-0317-42AE-98E3-4101D4568452}'
- InstallerLocale: de
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026.exe
  InstallerSha256: 01CD6CA43CAAFABC9D20EBC37D61920547C94549898BED8F825B8D78FA475FF6
  ProductCode: '{3BD2CA68-013A-40D0-B425-0F1DB18A0B3A}'
- InstallerLocale: de
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/MissionKitEnt2026_x64.exe
  InstallerSha256: EF816BA7866CA601FFE0FCEE95B5D7699BD5E5F183D1D2550ACBEAD49BA8E538
  ProductCode: '{3039641E-0317-42AE-98E3-4101D4568452}'
ManifestType: installer
ManifestVersion: 1.10.0
