# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: OpenShot.OpenShot
PackageVersion: 3.3.0
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
FileExtensions:
- .osp
ProductCode: '{code:GetAppId|{{4BB0DCDC-BC24-49EC-8937-72956C33A470}}_is1'
ReleaseDate: 2024-07-11
AppsAndFeaturesEntries:
- Publisher: OpenShot Studios, LLC
  DisplayVersion: 3.2.1
  ProductCode: '{code:GetAppId|{{4BB0DCDC-BC24-49EC-8937-72956C33A470}}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '{code:GetDefaultDirName|OpenShot Video Editor}'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/OpenShot/openshot-qt/releases/download/v3.2.1/OpenShot-v3.2.1-x86.exe
  InstallerSha256: F43FC670E0B21FD59A30FADF18581853D8030422E4CE06ABC13238586D195F1D
- Architecture: x64
  InstallerUrl: https://github.com/OpenShot/openshot-qt/releases/download/v3.2.1/OpenShot-v3.2.1-x86_64.exe
  InstallerSha256: FA13E2E48E0B4C25C3AE38F1418D90B967001BEEDBC8891B6CCFCB9D54118630
ManifestType: installer
ManifestVersion: 1.9.0
