# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.71.4
Scope: machine
UpgradeBehavior: install
Protocols:
- blizzv1
- teamviewer10
- teamviewer8
- teamviewerapi
- tvchat1
- tvcontrol1
- tvfiletransfer1
- tvjoinv8
- tvoneweblogin
- tvpresent1
- tvsendfile1
- tvsqcustomer1
- tvsqsupport1
- tvvideocall1
- tvvpn1
FileExtensions:
- tpsr
- tvc
- tvlink
- tvs
ReleaseDate: 2025-10-28
Installers:
- Architecture: neutral
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Full/TeamViewer_Full.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: B97D5776D42274EEBF3F79B1B9D20E93C8E1A2FEA277EFD6AB864A9CB4907FB1
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{361205DC-CE77-4B86-BF1A-2E00244CE792}'
  AppsAndFeaturesEntries:
  - ProductCode: '{361205DC-CE77-4B86-BF1A-2E00244CE792}'
    UpgradeCode: '{F0C19578-BC20-4F79-B2C3-EA824DE91F34}'
- Architecture: neutral
  InstallerType: zip
  NestedInstallerType: wix
  NestedInstallerFiles:
  - RelativeFilePath: Full/TeamViewer_Full.msi
  InstallerUrl: https://download.teamviewer.com/download/version_15x/TeamViewer_MSI64.zip
  InstallerSha256: B97D5776D42274EEBF3F79B1B9D20E93C8E1A2FEA277EFD6AB864A9CB4907FB1
  InstallerSwitches:
    InstallLocation: INSTALLFOLDER="<INSTALLPATH>"
  ProductCode: '{D2614F85-9D2D-43F6-9A9A-BE7D1E8C2CD9}'
  AppsAndFeaturesEntries:
  - ProductCode: '{D2614F85-9D2D-43F6-9A9A-BE7D1E8C2CD9}'
    UpgradeCode: '{98A72954-BC0F-11E8-9CC6-3F794D8C2BDE}'
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup.exe
  InstallerSha256: 4882C40D3326E0A38989C87B02094EC38123CFE7963DDE0F41C56BD3B4AD784D
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://download.teamviewer.com/download/TeamViewer_Setup_x64.exe
  InstallerSha256: 9882842974CE85027588B881AA9FB043BD3BDD6961262F518C4AD425AE82E708
ManifestType: installer
ManifestVersion: 1.10.0
