# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: TeamViewer.TeamViewer
PackageVersion: 15.71.4
PackageLocale: de-DE
PublisherUrl: https://www.teamviewer.com/de/
PublisherSupportUrl: https://www.teamviewer.com/de/global/support/customer-support/
PrivacyUrl: https://www.teamviewer.com/de/legal/privacy-and-cookies/
PackageUrl: https://www.teamviewer.com/de/download/windows/
License: Proprietäre
LicenseUrl: https://www.teamviewer.com/de/legal/eula/
CopyrightUrl: https://www.teamviewer.com/de/legal/eula/
ShortDescription: Sicherer Remote Access und Support
Description: |-
  TeamViewer ist eine umfassende Lösung für Fernzugriff, Fernsteuerung und Fernsupport, die mit fast jeder Desktop- und Mobilplattform funktioniert, einschließlich Windows, macOS, Android und iOS.
  Mit TeamViewer können Sie sich per Fernzugriff auf Computer oder mobile Geräte an jedem Ort der Welt einwählen und sie so nutzen, als wären Sie vor Ort.
Tags:
- fernsteuerung
- fernzugriff
- konferenzen
- remote-control
- remote-desktop
- webkonferenz
ReleaseNotes: |-
  New Features
  - Erleben Sie das brandneue TeamViewer Remote!

  Improvements
  - Geben Sie uns gerne Feedback zu den neuesten und zukünftigen Verbesserungen der Benutzeroberfläche: An Umfrage teilnehmen

  Bugfixes
  - Kleinere Fehlerbehebung zur Reduzierung der Last beim Start des Clients.
PurchaseUrl: https://www.teamviewer.com/de/pricing/
Documentations:
- DocumentLabel: Knowledge Base
  DocumentUrl: https://www.teamviewer.com/de/global/support/knowledge-base/
ManifestType: locale
ManifestVersion: 1.10.0
