# Created with komac v2.6.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: SnapmakerDevTeam.SnapmakerLuban
PackageVersion: 4.14.0
PackageLocale: en-US
Publisher: Snapmaker Dev Team
PublisherUrl: https://snapmaker.com/
PublisherSupportUrl: https://github.com/Snapmaker/Luban/issues
Author: Snapmaker Dev Team
PackageName: Snapmaker Luban
PackageUrl: https://github.com/Snapmaker/Luban/releases
License: AGPL-3.0
LicenseUrl: https://github.com/Snapmaker/Luban/blob/HEAD/LICENSE
Copyright: Copyright (c) 2021 Snapmaker Dev Team
CopyrightUrl: https://raw.githubusercontent.com/Snapmaker/Luban/master/LICENSE
ShortDescription: Snapmaker 3-in-1 Software for 3D Printing, Laser Engraving and CNC Cutting.
Moniker: snapmakerluban
Tags:
- 3d
- 3d-printer
- 3d-printing
ReleaseNotes: |-
  Feature
  - Allows users to use OrcaSlicer to upload sliced ​​gcode directly to the machine and print it when running Snapmaker Luban and connected to the printer via wifi.(Protocol:octo/kilpper,Port:5000)
  - Add Snapmaker user portal
  Improvements
  - Improvement: CNC machining tool name adjustment
  - Improvement: A150 machine is compatible with 2W and 20W laser modules
  - Improvement: Mac icon optimization
  - Improvement: Cancel forced scaling of DXF files
  Bug Fixes
  - Fix the issue where laser/cnc might fail to generate toolpath on the Windows platform.
  - Fix SVG file import and parsing issues
  - Fix case library 3mf opening pop-up issue
ReleaseNotesUrl: https://github.com/Snapmaker/Luban/releases/tag/v4.14.0
ManifestType: defaultLocale
ManifestVersion: 1.6.0
