# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: appmakes.Typora
PackageVersion: 1.12.1
InstallerLocale: en-US
InstallerType: inno
UpgradeBehavior: install
FileExtensions:
- apib
- markdown
- md
- mdown
- mdtext
- mdtxt
- mdwn
- mdx
- mkd
- mmd
- qmd
- rmarkdown
- rmd
- text
- txt
ProductCode: '{37771A20-7167-44C0-B322-FD3E54C56156}_is1'
ReleaseDate: 2025-09-19
AppsAndFeaturesEntries:
- ProductCode: '{37771A20-7167-44C0-B322-FD3E54C56156}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://downloads.typoraio.cn/windows/typora-setup-ia32-1.12.1.exe
  InstallerSha256: 83955EA661051DFDF8239F5BFF4A6C9AE199B22A10768F0D76A2A73DA3AFC0BC
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x86
  Scope: machine
  InstallerUrl: https://downloads.typoraio.cn/windows/typora-setup-ia32-1.12.1.exe
  InstallerSha256: 83955EA661051DFDF8239F5BFF4A6C9AE199B22A10768F0D76A2A73DA3AFC0BC
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Typora'
- Architecture: x64
  Scope: user
  InstallerUrl: https://downloads.typoraio.cn/windows/typora-setup-x64-1.12.1.exe
  InstallerSha256: 30AE6FA152F5090B10353F6FED3B8B7531653C4B1FD8A0976AF9AC376C620D9A
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: x64
  Scope: machine
  InstallerUrl: https://downloads.typoraio.cn/windows/typora-setup-x64-1.12.1.exe
  InstallerSha256: 30AE6FA152F5090B10353F6FED3B8B7531653C4B1FD8A0976AF9AC376C620D9A
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Typora'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://downloads.typoraio.cn/windows/typora-setup-arm64-1.12.1.exe
  InstallerSha256: 47E656093BD0B3E5C8B398EF23E5EBA82B948DF9CDCD0778F48E4E342160141D
  InstallerSwitches:
    Custom: /CURRENTUSER
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://downloads.typoraio.cn/windows/typora-setup-arm64-1.12.1.exe
  InstallerSha256: 47E656093BD0B3E5C8B398EF23E5EBA82B948DF9CDCD0778F48E4E342160141D
  InstallerSwitches:
    Custom: /ALLUSERS
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Typora'
ManifestType: installer
ManifestVersion: 1.10.0
