# Automatically updated by the winget bot at 2026/Oct/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Tencent.WorkBuddy
PackageVersion: 5.4.7
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: BFD312E9-1019-4F57-9F44-F86246833B50
ReleaseDate: 2026-09-01
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.4.7.37521366-b148bd1d.exe
  InstallerSha256: 1B01BF15A5787400A683521AC0337F6051D92A4E80018EF6296598DF5D896DA0
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.4.7.37521366-b148bd1d.exe
  InstallerSha256: 1B01BF15A5787400A683521AC0337F6051D92A4E80018EF6296598DF5D896DA0
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.28.0
