# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: TeraTermProject.teraterm5
PackageVersion: 5.7.1
InstallerLocale: en-US
InstallerType: inno
Scope: machine
InstallerSwitches:
  Silent: /Silent
  SilentWithProgress: /Silent
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\teraterm5'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/TeraTermProject/teraterm/releases/download/v5.7.1/teraterm-5.7.1-x86.exe
  InstallerSha256: 88BF481C67E9DE7037A5E986E9F5F860F8C70832B456E936CAC6C593FDD37950
  ProductCode: '{07A7E17A-F6D6-44A7-82E6-6BEE528CCA2A}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: Tera Term 5.5.2 x86
    ProductCode: '{07A7E17A-F6D6-44A7-82E6-6BEE528CCA2A}_is1'
- Architecture: x64
  InstallerUrl: https://github.com/TeraTermProject/teraterm/releases/download/v5.7.1/teraterm-5.7.1-x64.exe
  InstallerSha256: A091233B41AD3EBD2277892AD9EF077148F1720171AE225C041E895E573343FE
  ProductCode: '{3F29ABAB-6EEF-40BF-B1EA-ACA276CB133B}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: Tera Term 5.5.2 x64
    ProductCode: '{3F29ABAB-6EEF-40BF-B1EA-ACA276CB133B}_is1'
- Architecture: arm64
  InstallerUrl: https://github.com/TeraTermProject/teraterm/releases/download/v5.7.1/teraterm-5.7.1-arm64.exe
  InstallerSha256: 24F28F6D78C0346012F6F7B7AF71BCE882CD168F13B9A205E826E7002C5BA340
  ProductCode: '{9D4C2E5D-2AA7-4041-A098-E6750542350E}_is1'
  AppsAndFeaturesEntries:
  - DisplayName: Tera Term 5.5.2 arm64
    ProductCode: '{9D4C2E5D-2AA7-4041-A098-E6750542350E}_is1'
ManifestType: installer
ManifestVersion: 1.12.0
ReleaseDate: 2026-10-09
