# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: JetBrains.IntelliJIDEA.Ultimate
PackageVersion: 2023.3.4
PackageLocale: en-US
Publisher: JetBrains s.r.o.
PublisherUrl: https://www.jetbrains.com/
PublisherSupportUrl: https://www.jetbrains.com/support/
PrivacyUrl: https://www.jetbrains.com/legal/docs/privacy/privacy/
Author: JetBrains s.r.o.
PackageName: IntelliJ IDEA Ultimate Edition
PackageUrl: https://www.jetbrains.com/idea/
License: Proprietary
LicenseUrl: https://www.jetbrains.com/legal/docs/toolbox/user/
Copyright: Copyright © 2000-2024 JetBrains s.r.o.
ShortDescription: The Leading Java and Kotlin IDE
Description: IntelliJ IDEA is undoubtedly the top-choice IDE for software developers. It makes Java and Kotlin development a more productive and enjoyable experience.
Moniker: intellij-idea-ultimate
Tags:
- code
- coding
- develop
- development
- java
- kotlin
- programming
PurchaseUrl: https://www.jetbrains.com/idea/buy/
Documentations:
- DocumentLabel: Resources
  DocumentUrl: https://www.jetbrains.com/idea/resources/
ManifestType: defaultLocale
ManifestVersion: 1.5.0
