# Created using wingetcreate 1.6.5.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: NordSecurity.NordPass
PackageVersion: 5.22.2
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: --updated
UpgradeBehavior: install
Protocols:
- nordpass
ProductCode: f7c32559-6c31-590a-9972-0bea54b04213
Installers:
- Architecture: x64
  InstallerUrl: https://downloads.npass.app/windows/NordPassSetup.exe
  InstallerSha256: 6DA05BAABB6152F1D38B02B94E555CF0C9B1975FF637FFA97B08802A345D8C55
ManifestType: installer
ManifestVersion: 1.6.0
