# Created with komac v2.2.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GitHub.GitHubDesktop
PackageVersion: 3.4.1
Platform:
- Windows.Desktop
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ReleaseDate: 2024-05-29
Installers:
- Architecture: x64
  InstallerType: exe
  Scope: user
  InstallerUrl: https://desktop.githubusercontent.com/github-desktop/releases/3.4.0-bd8f79d7/GitHubDesktopSetup-x64.exe
  InstallerSha256: 44327126856F36A8D29044BBFED227A6AF6D9811FE42CA2F2C06476EA4BC2724
  InstallerSwitches:
    Silent: /s
    SilentWithProgress: /s
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://desktop.githubusercontent.com/github-desktop/releases/3.4.0-bd8f79d7/GitHubDesktopSetup-x64.msi
  InstallerSha256: CC3419BDD284D9058A159631BEB0250DB3E9638943C5A6EE6B084CE9CEB78E3B
  ProductCode: '{538F6780-68EE-41A6-9804-53AF244D4530}'
  AppsAndFeaturesEntries:
  - DisplayName: GitHub Desktop Deployment Tool
    DisplayVersion: 3.4.0.0
    UpgradeCode: '{00D8E2EE-13EA-5BEB-87F0-70EFC46A7D4A}'
ManifestType: installer
ManifestVersion: 1.6.0
