# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Dell.PeripheralManager
PackageVersion: 2.0.0.72
InstallerLocale: en-US
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ReleaseDate: 2025-02-19
AppsAndFeaturesEntries:
- DisplayName: Dell Peripheral Manager
  Publisher: Dell Inc.
Installers:
- Architecture: x86
  InstallerUrl: https://dl.dell.com/FOLDER12741180M/1/DDPM-Setup_2.0.0.72.exe
  InstallerSha256: 10AA8E15581A7F79A56D3F78D54B67AB9F84D4D98AE5F59D3F727C9743725244
ManifestType: installer
ManifestVersion: 1.9.0
