# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Dell.PeripheralManager
PackageVersion: 2.0.0.72
PackageLocale: en-US
Publisher: Dell Inc.
PublisherUrl: https://www.dell.com/
PublisherSupportUrl: https://www.dell.com/support/home/
PackageName: Dell Peripheral Manager
PackageUrl: https://www.dell.com/support/home/zh-cn/product-support/product/dell-peripheral-manager/drivers
License: Proprietary
Copyright: Copyright (C) 2021-2024 Dell Inc.
ShortDescription: |-
  The Dell Peripheral Manager software enables you to customize and manage your Dell peripherals
  such as keyboards, mice, and webcams.
InstallationNotes: In order to make sure the software works properly, system reboot is recommended.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
