# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Syntevo.SmartGit
PackageVersion: 26.1.057
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: smartgit-26_1_057-setup.exe
Scope: machine
InstallModes:
- interactive
- silent
UpgradeBehavior: install
Commands:
- /NORESTART
- /SP-
- /SUPPRESSMSGBOXES
- /VERYSILENT
ReleaseDate: 2026-10-03
AppsAndFeaturesEntries:
- Publisher: syntevo GmbH
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\SmartGit'
Installers:
- Architecture: x86
  InstallerUrl: https://download.smartgit.dev/smartgit/smartgit-26_1_057-win-installer.zip
  InstallerSha256: 1980EA2627CA314EEAD64FD768603C682C593CB3F03AB4905621D6D6EECBB0A0
ManifestType: installer
ManifestVersion: 1.12.0
