# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Foxit.FoxitReader
PackageVersion: 2024.2.2.25170
Scope: machine
UpgradeBehavior: install
Protocols:
- foxitpdfreader
- foxitreader
FileExtensions:
- cpdf
- fdf
- pdf
- ppdf
- xdp
- xfdf
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/2023.2.0/FoxitPDFReader20232_L10N_Setup.exe
  InstallerSha256: 1E894717AAD5378FC61DA46C51AF7345274D2CB922F6ECDFABF11C5DEB0EBE6F
  InstallModes:
  - interactive
  - silent
  InstallerSwitches:
    Silent: /quiet
    SilentWithProgress: /quiet
    Log: /log "<LOGPATH>"
  ExpectedReturnCodes:
  - InstallerReturnCode: 6
    ReturnResponse: cancelledByUser
  - InstallerReturnCode: 1601
    ReturnResponse: contactSupport
  - InstallerReturnCode: 1602
    ReturnResponse: cancelledByUser
  - InstallerReturnCode: 1618
    ReturnResponse: installInProgress
  - InstallerReturnCode: 1623
    ReturnResponse: systemNotSupported
  - InstallerReturnCode: 1625
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1628
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 1633
    ReturnResponse: systemNotSupported
  - InstallerReturnCode: 1638
    ReturnResponse: alreadyInstalled
  - InstallerReturnCode: 1639
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 1641
    ReturnResponse: rebootInitiated
  - InstallerReturnCode: 1640
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1643
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1644
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1649
    ReturnResponse: blockedByPolicy
  - InstallerReturnCode: 1650
    ReturnResponse: invalidParameter
  - InstallerReturnCode: 1654
    ReturnResponse: systemNotSupported
  - InstallerReturnCode: 3010
    ReturnResponse: rebootRequiredToFinish
  AppsAndFeaturesEntries:
  - UpgradeCode: '{9D148992-FACF-4107-84A3-C48F19CF0B57}'
    InstallerType: wix
- Architecture: x86
  InstallerType: inno
  InstallerUrl: https://cdn01.foxitsoftware.com/product/phantomPDF/desktop/win/2023.2.0/FoxitPDFReader20232_L10N_Setup_Prom.exe
  InstallerSha256: 6EE026B0AA76A918780CAE66C0D1ACF9D6EC4B1AF46554FC42F3B863E11F5B6D
  ProductCode: Foxit Reader_is1
ManifestType: installer
ManifestVersion: 1.6.0
