# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: BellSoft.LibericaNIK.23.JDK17.Full
PackageVersion: 24.1.2
PackageLocale: en-US
Publisher: BellSoft
PublisherUrl: https://bell-sw.com/
PublisherSupportUrl: https://github.com/bell-sw/LibericaNIK/issues
PackageName: Liberica NIK 23 Full (JDK 17)
PackageUrl: https://bell-sw.com/liberica-native-image-kit/
License: GPL 2 with Classpath Exception
LicenseUrl: https://bell-sw.com/liberica_nik_eula/
ShortDescription: Liberica NIK is a multilingual tool that transforms your applications into performant native images
Tags:
- graalvm
- java
- javafx
- liberica
- native-image
- openjdk
ReleaseNotesUrl: https://github.com/bell-sw/LibericaNIK/releases/tag/24.1.2+1-23.0.2+9
ManifestType: defaultLocale
ManifestVersion: 1.9.0
