# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Bitvise.SSH.Client
PackageVersion: "9.32"
InstallerLocale: en-US
InstallerType: exe
InstallModes:
- silentWithProgress
InstallerSwitches:
  Silent: -acceptEULA
  SilentWithProgress: -acceptEULA
UpgradeBehavior: uninstallPrevious
Protocols:
- ssh
FileExtensions:
- bscp
- tlp
ProductCode: '{CF8E6E00-9C03-4440-81C0-21FACB921A6B}'
Installers:
- Architecture: neutral
  InstallerUrl: https://dl.bitvise.com/BvSshClient-Inst.exe
  InstallerSha256: 1E6CC0048D6AB0C6A9012A949B5A8F60926B93766AE2A4B35A0EEFB672D1DED0
ManifestType: installer
ManifestVersion: 1.5.0
