# Created with komac v2.2.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Docker.DockerDesktop
PackageVersion: 4.30.0
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: install --quiet
  SilentWithProgress: install --quiet
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: alreadyInstalled
UpgradeBehavior: install
ProductCode: '{E60243DE-EC8F-4F99-BBB9-09D1E336F46F}'
ReleaseDate: 2024-05-06
AppsAndFeaturesEntries:
- UpgradeCode: '{0C509387-E4AE-4918-9D60-E68A16D1B709}'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://desktop.docker.com/win/main/amd64/149282/DockerDesktop.msi
  InstallerSha256: C53DC52E63A67DA706A1676AEFC040833371A095B7385BFAD3F87FD235975371
ManifestType: installer
ManifestVersion: 1.6.0
