# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: RingCentral.RingCentral
PackageVersion: 25.3.2015.1057
PackageLocale: en-US
Publisher: RingCentral
PublisherUrl: https://www.ringcentral.com/
PublisherSupportUrl: https://support.ringcentral.com/
PrivacyUrl: https://www.ringcentral.com/legal/privacy-notice.html
Author: RingCentral, Inc.
PackageName: RingCentral
PackageUrl: https://www.ringcentral.com/download.html
License: Proprietary
LicenseUrl: https://www.ringcentral.com/legal/eulatos.html
Copyright: Copyright © 1999-2024 RingCentral, Inc. All rights reserved.
CopyrightUrl: https://partners.ringcentral.com/content/PublicFile/RingCentral_Co-Branding_Guidelines.pdf
ShortDescription: Communicate your way with team messaging, video meetings, and a modern business phone—all in one place.
Tags:
- chat
- collaborate
- collaboration
- conference
- conferencing
- meeting
- video-conferencing
- voice-conferencing
- webinar
PurchaseUrl: https://www.ringcentral.com/office/plansandpricing.html
ManifestType: defaultLocale
ManifestVersion: 1.10.0
