# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.10.0.schema.json

PackageIdentifier: RingCentral.RingCentral
PackageVersion: 25.3.2015.1057
PackageLocale: zh-CN
Publisher: RingCentral
PublisherUrl: https://www.ringcentral.com/cn/zh/
PublisherSupportUrl: https://support.ringcentral.com/
PrivacyUrl: https://www.ringcentral.com/cn/zh/privacy-notice.html
Author: RingCentral, Inc.
PackageName: RingCentral
PackageUrl: https://www.ringcentral.com/download.html
License: 专有软件
LicenseUrl: https://www.ringcentral.com/legal/eulatos.html
Copyright: 版权 © 1999-2024 RingCentral, Inc. 保留所有权利.
CopyrightUrl: https://partners.ringcentral.com/content/PublicFile/RingCentral_Co-Branding_Guidelines.pdf
ShortDescription: 通过团队消息、视频会议和现代商务电话进行沟通，一切尽在其中。
Tags:
- 会议
- 协作
- 协同
- 开会
- 研讨会
- 聊天
- 视频会议
- 语音会议
PurchaseUrl: https://www.ringcentral.com/office/plansandpricing.html
ManifestType: locale
ManifestVersion: 1.10.0
