# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Micronaut.Launch
PackageVersion: 4.7.6
PackageLocale: en-US
Publisher: Micronaut Foundation
PublisherUrl: https://micronaut.io/
PublisherSupportUrl: https://github.com/micronaut-projects/micronaut-starter/issues
PackageName: Micronaut Launch
PackageUrl: https://github.com/micronaut-projects/micronaut-starter
License: Apache-2.0
LicenseUrl: https://github.com/micronaut-projects/micronaut-starter/blob/HEAD/LICENSE
ShortDescription: Micronaut - A modern, JVM-based (Java, Groovy, Kotlin), full-stack framework for building modular and testable microservice and serverless applications
Moniker: micronaut
ReleaseNotes: |-
  What's Changed
  - Feature disabled by @sdelamo in #2702
  Full Changelog: v4.7.5...v4.7.6
ReleaseNotesUrl: https://github.com/micronaut-projects/micronaut-starter/releases/tag/v4.7.6
ManifestType: defaultLocale
ManifestVersion: 1.9.0
