# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Linewize.Connect
PackageVersion: 4.3.1
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: '{27332A44-7F96-47CC-8E7F-D770AD7CFE5E}'
ReleaseDate: 2025-08-05
AppsAndFeaturesEntries:
- DisplayName: Connect
  DisplayVersion: 4.3.1.1318
  ProductCode: '{27332A44-7F96-47CC-8E7F-D770AD7CFE5E}'
  UpgradeCode: '{6AD92DBB-ED93-4C19-9D72-86B5E2E3BD0B}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\[BZ.COMPANYNAME]'
Installers:
- Architecture: x64
  InstallerUrl: https://qoria-mza-installers.linewize.net/Connect%20Installer.msi
  InstallerSha256: A0E29CEFE43D282F3BD723374954725D480D6A5859AAFA4F15B3A152F2C6F220
ManifestType: installer
ManifestVersion: 1.10.0

