# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Clockify.Clockify
PackageVersion: 1.8.3
InstallerLocale: en-US
InstallerType: msi
Scope: user
InstallModes:
- interactive
- silent
UpgradeBehavior: install
ProductCode: '{711E756D-1ED5-4C51-A29C-76BEE790F3CB}'
ReleaseDate: 2025-02-26
AppsAndFeaturesEntries:
- Publisher: COING Inc.
  ProductCode: '{711E756D-1ED5-4C51-A29C-76BEE790F3CB}'
  UpgradeCode: '{A17CEE88-470D-49D0-A58D-40D503A0BEBF}'
InstallationMetadata: {}
Installers:
- Architecture: x64
  InstallerUrl: https://clockify.me/downloads/clockify-setup.msi
  InstallerSha256: BC955BBFF80062C23D5D9778FE68D7717E84108CB1033A0D215FAA0C50758225
ManifestType: installer
ManifestVersion: 1.9.0
