# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: HandBrake.HandBrake
PackageVersion: 1.8.1
PackageLocale: en-US
Publisher: The HandBrake Team
PublisherUrl: https://github.com/HandBrake/HandBrake
PublisherSupportUrl: https://github.com/HandBrake/HandBrake/issues
Author: The HandBrake Team
PackageName: HandBrake
License: GNU General Public License v2
LicenseUrl: https://github.com/HandBrake/HandBrake/blob/HEAD/LICENSE
CopyrightUrl: https://raw.githubusercontent.com/HandBrake/HandBrake/master/LICENSE
ShortDescription: HandBrake is a tool for converting video from nearly any format to a selection of modern, widely supported codecs.
Moniker: handbrake
Tags:
- media
- transcode
- video
- video-transcoding
ManifestType: defaultLocale
ManifestVersion: 1.6.0
