# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: GIMP.GIMP.2
PackageVersion: 3.0.6.1
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: inno
UpgradeBehavior: install
FileExtensions:
- 3fr
- alpha
- als
- apm
- ari
- arw
- avif
- bay
- bitmap
- bmp
- bw
- cap
- cel
- cin
- cine
- cr2
- cr3
- crw
- cs1
- data
- dc2
- dcm
- dcr
- dds
- desktop
- dicom
- dng
- eps
- erf
- exr
- fff
- fit
- fits
- flc
- fli
- g3
- gbp
- gbr
- gif
- gih
- hdr
- heic
- heif
- hgt
- ia
- icb
- ico
- icon
- iiq
- im1
- im24
- im32
- im8
- j2c
- j2k
- jp2
- jpc
- jpe
- jpeg
- jpg
- k25
- kc2
- kdc
- mask
- matte
- mdc
- mef
- mos
- mrw
- nef
- nrw
- ora
- orf
- pat
- pbm
- pcc
- pcx
- pdf
- pef
- pfm
- pgm
- pix
- png
- pnm
- ppm
- ps
- psd
- psp
- pspimage
- pxn
- qtk
- ra
- raf
- ras
- raw
- rdc
- rgb
- rgba
- rw2
- rwl
- sgi
- sr2
- srf
- srw
- sti
- sun
- svg
- tga
- tif
- tiff
- tub
- vda
- vst
- webp
- wmf
- x3f
- xbm
- xcf
- xcf.bz2
- xcf.gz
- xcfbz2
- xcfgz
- xcfxz
- xpm
- xwd
ProductCode: GIMP-3_is1
ReleaseDate: 2025-10-07
AppsAndFeaturesEntries:
- ProductCode: GIMP-3_is1
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://download.gimp.org/gimp/v3.0/windows/gimp-3.0.6-setup-1.exe
  InstallerSha256: 1521AE318FF176D3D428279D52FF5ABDF328DDF8644B48DE75684E55E1057167
  InstallerSwitches:
    Custom: /CURRENTUSER /VERYSILENT
- Architecture: x86
  Scope: machine
  InstallerUrl: https://download.gimp.org/gimp/v3.0/windows/gimp-3.0.6-setup-1.exe
  InstallerSha256: 1521AE318FF176D3D428279D52FF5ABDF328DDF8644B48DE75684E55E1057167
  InstallerSwitches:
    Custom: /ALLUSERS /VERYSILENT
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\GIMP 3'
ManifestType: installer
ManifestVersion: 1.10.0
