# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Grammarly.Grammarly
PackageVersion: 1.2.57.1263
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Upgrade: /update
UpgradeBehavior: install
ProductCode: Grammarly Desktop Integrations
Installers:
- Architecture: x86
  InstallerUrl: https://download-windows.grammarly.com/versions/1.2.57.1263/GrammarlyInstaller.exe
  InstallerSha256: AB8C6C68BC7AB8041DA39D7BEDB65F86564396BB3B4646D4790867A3D4DBF907
- Architecture: x64
  InstallerUrl: https://download-windows.grammarly.com/versions/1.2.57.1263/GrammarlyInstaller.exe
  InstallerSha256: AB8C6C68BC7AB8041DA39D7BEDB65F86564396BB3B4646D4790867A3D4DBF907
ManifestType: installer
ManifestVersion: 1.5.0
