# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: Miro.Miro
PackageVersion: 0.8.68
PackageLocale: en-US
Publisher: Miro
PublisherUrl: https://miro.com/
PrivacyUrl: https://miro.com/legal/privacy-policy/
Author: Miro
PackageName: Miro
PackageUrl: https://miro.com/
License: Proprietary
LicenseUrl: https://miro.com/legal/terms-of-service/
Copyright: Copyright (c) 2022 Miro
ShortDescription: The online collaborative platform to bring teams together, anytime, anywhere.
Moniker: miro
Tags:
- collaboration
- project-management
- whiteboard
ManifestType: defaultLocale
ManifestVersion: 1.6.0
