# Automatically updated by the winget bot at 2026/Oct/11
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.28.0.schema.json

PackageIdentifier: Tencent.WorkBuddy
PackageVersion: 5.5.6
InstallerType: nullsoft
UpgradeBehavior: install
ProductCode: BFD312E9-1019-4F57-9F44-F86246833B50
ReleaseDate: 2026-09-10
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.5.6.38337834-5f969292.exe
  InstallerSha256: F852C2879CB2B44E83EF65ED956ABBD442612C6759C8D785EB3D3129C4A74E58
  InstallerSwitches:
    Custom: /currentuser
- Architecture: x64
  Scope: machine
  InstallerUrl: https://download.codebuddy.cn/workbuddy/saas/win32-x64-user/WorkBuddy-win32-x64-user-5.5.6.38337834-5f969292.exe
  InstallerSha256: F852C2879CB2B44E83EF65ED956ABBD442612C6759C8D785EB3D3129C4A74E58
  InstallerSwitches:
    Custom: /allusers
ManifestType: installer
ManifestVersion: 1.28.0
