# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AnyDeskSoftwareGmbH.AnyDesk
PackageVersion: 9.0.3
Platform:
- Windows.Desktop
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
Installers:
- Architecture: x86
  InstallerType: exe
  InstallerUrl: https://download.anydesk.com/AnyDesk.exe
  InstallerSha256: 5ABDA35B66C062351DDFE7BA435B1CBCECA98F822ADB3C254562C5988AB065C0
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Upgrade: --remove-first
    Custom: --install "C:\Program Files (x86)\AnyDesk" --update-auto --create-desktop-icon --create-shortcuts
  UpgradeBehavior: install
  ElevationRequirement: elevationRequired
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: msi
  InstallerUrl: https://download.anydesk.com/AnyDesk.msi
  InstallerSha256: 9F32CDA20CAC7AFAB4BF2ECFD2B080CC4F1F700DFF13566468DA69059B7EBF03
  UpgradeBehavior: uninstallPrevious
  ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk MSI
    Publisher: AnyDesk Software GmbH
    ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
    UpgradeCode: '{ED0600A3-9843-4B5B-B47F-586E1C3FC53A}'
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.9.0
