# Created using wingetcreate 1.5.7.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Amazon.AWSVPNClient
PackageVersion: 3.11.0
InstallerLocale: en-US
InstallerType: wix
ProductCode: '{E492293B-1CB5-4E6D-87FF-2459AD900515}'
Installers:
- Architecture: x64
  InstallerUrl: https://d20adtppz83p9s.cloudfront.net/WPF/3.11.0/AWS_VPN_Client.msi
  InstallerSha256: 9B6B7DEF99D76C59A97B067B6A73BDC6EE1C6B89A2063286F542E96B32DF5AE9
ManifestType: installer
ManifestVersion: 1.5.0
