# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: DanielMcGuireCorporation.MathBotCLI
PackageVersion: 3.4.0.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.DotNet.DesktopRuntime.8
ProductCode: MathBotCLI
ReleaseDate: 2024-05-13
AppsAndFeaturesEntries:
- DisplayName: MathBotCLI - Command Line Calculator
  Publisher: '"Daniel McGuire Corporation"'
  DisplayVersion: '"3.4.0.0"'
  ProductCode: MathBotCLI
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\MathBotCLI'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Daniel-McGuire-Corporation/MathBotCLI/releases/download/v3.4.0.0/MathBotCLI3.4Setup.exe
  InstallerSha256: 6ADB8899EB309EDDB86D7AD37B024E336CD1D50608C6ACAD2ACF5EDF118C1ABE
ManifestType: installer
ManifestVersion: 1.9.0
