# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Inkscape.Inkscape
PackageVersion: 1.4.2
PackageLocale: en-US
Publisher: Inkscape
PublisherUrl: https://inkscape.org/
PublisherSupportUrl: https://inkscape.org/community/
PrivacyUrl: https://inkscape.org/about/privacy/
PackageName: Inkscape
PackageUrl: https://inkscape.org/release/
License: GPL-2.0
LicenseUrl: https://inkscape.org/about/license/
Copyright: © 2023 Inkscape Developers
ShortDescription: A professional vector graphics software which runs on Linux, macOS and Windows desktop computers.
Description: |-
  Inkscape is a Free and open source vector graphics editor for GNU/Linux, Windows and macOS. It offers a rich set of features and is widely used for both artistic and technical illustrations such as cartoons, clip art, logos, typography, diagramming and flowcharting. It uses vector graphics to allow for sharp printouts and renderings at unlimited resolution and is not bound to a fixed number of pixels like raster graphics. Inkscape uses the standardized SVG file format as its main format, which is supported by many other applications including web browsers.
  It can import and export various file formats, including SVG, AI, EPS, PDF, PS and PNG. It has a comprehensive feature set, a simple interface, multi-lingual support and is designed to be extensible; users can customize Inkscape's functionality with add-ons.
  The Inkscape project has a growing international user community, and many learning materials exist to help get you started with your creations. Help and support is provided by the community, and there are lots of ways for you to get involved if you want to help improve the Inkscape project.
  Inkscape is a member of the Software Freedom Conservancy, a US 501(c)(3) non-profit organization. Contributions to Inkscape are tax deductible in the United States.
Moniker: inkscape
Tags:
- art
- draw
- drawing
- editor
- graphics
- svg
- vector-graphics
Documentations:
- DocumentLabel: Learn
  DocumentUrl: https://inkscape.org/learn/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
