# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: openobserve.openobserve
PackageVersion: 0.14.3
PackageLocale: en-US
Publisher: OpenObserve
PublisherUrl: https://github.com/openobserve
PublisherSupportUrl: https://github.com/openobserve/openobserve/issues
PackageName: OpenObserve
PackageUrl: https://github.com/openobserve/openobserve
License: AGPL-3.0
LicenseUrl: https://github.com/openobserve/openobserve/blob/HEAD/LICENSE
ShortDescription: A cloud native observability platform built specifically for logs, metrics, traces and analytics.
Tags:
- analytics
- datadog
- elasticsearch
- jaeger
- kibana
- log-analytics
- log-management
- log-search
- logs
- metrics
- monitoring
- observability
- opentelemetry
- prometheus
- rust-lang
- traces
ReleaseNotes: |-
  What's Changed
  - fix: test by @Loaki07 in #5830
  - fix: Y-axis max value formatting issue in trellis by @omkarK06 in #5829
  - fix: added separator by @harshiv-7 in #5820
  - fix: migrations for longtext by @oasisk in #5831
  - fix: Omit cached responses older than stream min_ts by @uddhavdave in #5610
  - fix: import dashboard issue with old versions by @ktx-abhay in #5835
  Full Changelog: v0.14.3-rc2...v0.14.3-rc3
ReleaseNotesUrl: https://github.com/openobserve/openobserve/releases/tag/v0.14.3-rc3
ManifestType: defaultLocale
ManifestVersion: 1.9.0
