# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: openobserve.openobserve
PackageVersion: 0.14.3
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: openobserve.exe
ReleaseDate: 2025-01-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/openobserve/openobserve/releases/download/v0.14.3-rc3/openobserve-v0.14.3-rc3-windows-amd64.zip
  InstallerSha256: 1DFB1E9F0F708F35132512C761C3A0C4B321FAAD9483B1DCBFABD338CBAB7516
ManifestType: installer
ManifestVersion: 1.9.0
