# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Automattic.Simplenote
PackageVersion: 2.23.0
PackageLocale: en-US
Publisher: Automattic, Inc.
PublisherUrl: https://github.com/Automattic/simplenote-electron
PublisherSupportUrl: https://github.com/Automattic/simplenote-electron/issues
PrivacyUrl: https://automattic.com/privacy
Author: Automattic, Inc.
PackageName: Simplenote
PackageUrl: https://simplenote.com/
License: GPL-2.0
LicenseUrl: https://github.com/Automattic/simplenote-electron/blob/HEAD/LICENSE.md
Copyright: Copyright (C) 1989, 1991 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/Automattic/simplenote-electron/develop/LICENSE.md
ShortDescription: Simplenote is an easy way to keep notes, lists, ideas and more. Your notes stay in sync with all your devices for free.
Moniker: simplenote
Tags:
- electron
- memo
- note
ReleaseNotes: |-
  Fixes
  - Fix WordPress.com login on the Electron builds #3281
  - Properly clear analytics cookies on logout #3269
ReleaseNotesUrl: https://github.com/Automattic/simplenote-electron/releases/tag/v2.23.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
