# Created with komac v2.9.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Mozilla.Thunderbird
PackageVersion: 128.6.1
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /S /PreventRebootRequired=true
  SilentWithProgress: /S /PreventRebootRequired=true
  InstallLocation: /InstallDirectoryPath="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- mailto
- mid
- webcal
- webcals
FileExtensions:
- eml
- ics
- wdseml
ReleaseDate: 2025-01-27
Installers:
- Architecture: x86
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/128.6.1esr/win32/en-US/Thunderbird%20Setup%20128.6.1esr.exe
  InstallerSha256: 4B0394B8E15546D99FAE00A0ACF75FA366AF727547D93C5B682C6D7BF35DBF2A
  ProductCode: Mozilla Thunderbird 128.6.0 (x86 en-US)
- Architecture: x64
  InstallerUrl: https://download-installer.cdn.mozilla.net/pub/thunderbird/releases/128.6.1esr/win64/en-US/Thunderbird%20Setup%20128.6.1esr.exe
  InstallerSha256: 546F68E0717EE2611E3E407A28C049308FDFCC8744BFD1736AA46D01A15F44D5
  ProductCode: Mozilla Thunderbird 128.6.0 (x64 en-US)
ManifestType: installer
ManifestVersion: 1.9.0
