# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.locale.1.9.0.schema.json

PackageIdentifier: RaoPics.RaoPics
PackageVersion: 1.0.0
PackageLocale: zh-CN
Publisher: meetqy
PublisherUrl: https://rao.pics/zh/
PublisherSupportUrl: https://github.com/rao-pics/rao-pics/issues
Author: meetqy
PackageName: Rao Pics
PackageUrl: https://rao.pics/zh/
License: GPL-3.0
LicenseUrl: https://github.com/rao-pics/rao-pics/blob/turbo-electron-prisma/LICENSE
Copyright: Copyright © 2022-2023 meetqy
ShortDescription: 任何设备可通过局域网访问素材/媒体/音乐。
Tags:
- 图像
- 图片
- 媒体
- 局域网
- 材料
- 素材
- 资源
- 音乐
- 音频
ReleaseNotes: |-
  - fix: 🐛 395-windows dark 模式显示异常 by @meetqy in #401
  - fix: 🐛 #399 未同步记录被遮挡 by @meetqy in #402
ManifestType: locale
ManifestVersion: 1.9.0
