# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Untis.Untis
PackageVersion: 2026.1.0
InstallerLocale: en-US
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
UpgradeBehavior: install
ProductCode: Untis 2026
ReleaseDate: 2025-07-30
AppsAndFeaturesEntries:
- DisplayName: Untis 2026
  DisplayVersion: '2026'
  ProductCode: Untis 2026
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Untis\2026'
Installers:
- Architecture: x64
  InstallerUrl: https://www.untis.at/fileadmin/downloads/2026/SetupUntis2026-x64.exe
  InstallerSha256: 04B1CA52BB0159A9EACA30D68E7A705E6136278EA6C4FD7170D8E7BFA0566C3E
ManifestType: installer
ManifestVersion: 1.10.0
