# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Morpheus.Bazarr
PackageVersion: '1.15'
PackageLocale: en-US
Publisher: Morpheus
PublisherUrl: https://www.bazarr.media/
PublisherSupportUrl: https://github.com/morpheus65535/bazarr/issues
Author: morpheus65535
PackageName: Bazarr
PackageUrl: https://github.com/morpheus65535/bazarr/releases/tag/v1.5.1
License: MIT
LicenseUrl: https://github.com/bazarr/bazarr.github.io/blob/HEAD/LICENSE
Copyright: Copyright (C) 2007 Free Software Foundation, Inc.
CopyrightUrl: https://raw.githubusercontent.com/morpheus65535/bazarr/master/LICENSE
ShortDescription: Bazarr is a companion application to Sonarr and Radarr that manages and downloads subtitles based on your requirements.
Moniker: bazarr
Tags:
- radarr
- sonarr
- subs
- subtitles
ReleaseNotes: |-
  - Prevent deletion of configs when reinstalling in a previous installation directory.
  - Properly clean, while uninstallating, files extracted from Bazarr release zip during installation.
ReleaseNotesUrl: https://github.com/bazarr/bazarr.github.io/releases/tag/v1.15
ManifestType: defaultLocale
ManifestVersion: 1.9.0
