# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Morpheus.Bazarr
PackageVersion: '1.15'
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: inno
NestedInstallerFiles:
- RelativeFilePath: Bazarr.exe
InstallModes:
- silent
- silentWithProgress
ProductCode: '{EEC3B85A-0666-4A5A-BD10-9BD1C237FEF0}_is1'
ReleaseDate: 2022-03-23
AppsAndFeaturesEntries:
- Publisher: Bazarr
  ProductCode: '{EEC3B85A-0666-4A5A-BD10-9BD1C237FEF0}_is1'
ElevationRequirement: elevatesSelf
InstallationMetadata:
  DefaultInstallLocation: '%SystemDrive%\Bazarr'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/bazarr/bazarr.github.io/releases/download/v1.15/Bazarr.zip
  InstallerSha256: 69DFD1591BB0B6F479FFBADF1EB563692DED7C909997425097602DDA63F496EC
ManifestType: installer
ManifestVersion: 1.9.0
