# Created with WinGet Releaser using komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2lab.Anchors
PackageVersion: 0.1.321
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17763.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: anchors.exe
  PortableCommandAlias: anchors
Commands:
- anchors
ReleaseDate: 2026-10-11
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.321/anchors_0.1.321_windows_amd64.zip
  InstallerSha256: 7D2EA23BDDA895FF24B956ED1B0C60A60CAECFEC81DD7515673D349ED278387E
- Architecture: arm64
  InstallerUrl: https://github.com/co2-lab/anchors/releases/download/v0.1.321/anchors_0.1.321_windows_arm64.zip
  InstallerSha256: 741C3F3CD7F751C49BF4D4C4BCF6BCDC988A049219D789016F27387211632719
ManifestType: installer
ManifestVersion: 1.12.0
