# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Bostrot.WSLManager
PackageVersion: 1.8.15
PackageLocale: en-US
Publisher: Bostrot
PublisherUrl: https://github.com/bostrot
PublisherSupportUrl: https://github.com/bostrot/wsl2-distro-manager/issues
PackageName: WSL Manager
PackageUrl: https://github.com/bostrot/wsl2-distro-manager
License: GPL-3.0
LicenseUrl: https://github.com/bostrot/wsl2-distro-manager/blob/HEAD/LICENSE
ShortDescription: A GUI to quickly manage your WSL2 instances.
Tags:
- collaborate
- docker
- flutter
- github
- gui
- rootfs
- turnkey
- windows
- wsl
- wsl2
ReleaseNotes: |-
  This is an automated release.
  What's Changed
  - Add Hungarian language by @RedyAu in #254
  - Launch with Terminal: Add fallback to PowerShell on exception by @RedyAu in #253
  - Use 7zip as archiver and merge tars instead of extracting
  - Upgrade packages by @bostrot in #264
  New Contributors
  - @RedyAu made their first contribution in #254
  Full Changelog: v1.8.14...v1.8.15
ReleaseNotesUrl: https://github.com/bostrot/wsl2-distro-manager/releases/tag/v1.8.15
ManifestType: defaultLocale
ManifestVersion: 1.9.0
