# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: calendulish.SteamToolsNG
PackageVersion: '4.0'
PackageLocale: en-US
Publisher: calendulish
PublisherUrl: https://lara.monster/
PublisherSupportUrl: https://github.com/calendulish/steam-tools-ng/issues/new/choose
Author: Lara Maia
PackageName: Steam Tools NG
PackageUrl: https://github.com/calendulish/steam-tools-ng
License: GPL-3.0
LicenseUrl: https://github.com/calendulish/steam-tools-ng/blob/HEAD/LICENSE
Copyright: Lara Maia <dev@lara.monster> 2024
ShortDescription: Useful tools for Steam
Description: Some useful tools to use with steam client or compatible programs and websites
Moniker: steam-tools-ng
Tags:
- games
- steam
- stlib
- valve
ReleaseNotes: |-
  ArchLinux:
  paru -S steam-tools-ng
  or
  pikaur -S steam-tools-ng
  Gentoo:
  eselect repository enable calendulish
  emaint sync --repo calendulish
  emerge steam-tools-ng
  Other Linux:
  pip install --user steam-tools-ng
  Windows:
  winget install steam-tools-ng
  or download and run steam-tools-ng-latest.exe bellow
  MacOS:
  MEEH!
  Changes:
  - New module added: Market Monitor
    this can be used to monitor price on Steam Market
  - pt_BR translation updated
    you can contribute on translation at transifex
  Fixes:
  - [steamguard] Fix a problem that causes minor desync in steamguard codes
  - [steamguard] Fix an exception when steamworks isn't available
  - [coupons] Fix missing target when sending trade offers
  - [login] Fix devkey not being updated due valve changes
  - [login] Fix "login with a new account" button not working
  - [login] Show auth code on login error
ReleaseNotesUrl: https://github.com/calendulish/steam-tools-ng/releases/tag/v4.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
