# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: Microsoft.Bicep
PackageVersion: 0.34.1
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://github.com/Azure/bicep
PublisherSupportUrl: https://github.com/Azure/bicep/issues
Author: Azure
PackageName: Bicep CLI
PackageUrl: https://github.com/Azure/bicep
License: MIT
LicenseUrl: https://github.com/Azure/bicep/blob/HEAD/LICENSE
Copyright: Copyright (c) Microsoft Corporation.
CopyrightUrl: https://raw.githubusercontent.com/Azure/bicep/main/LICENSE
ShortDescription: Bicep is a Domain Specific Language (DSL) for deploying Azure resources declaratively. It aims to drastically simplify the authoring experience with a cleaner syntax and better support for modularity and code re-use.
Moniker: bicep
Tags:
- arm-templates
- azure
- bicep
- bicep-cli
ReleaseNotesUrl: https://github.com/Azure/bicep/releases/tag/v0.34.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/Azure/bicep/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
