# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Foxit.FoxitReader
PackageVersion: 2025.2.0.33046
InstallerType: burn
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /quiet
  SilentWithProgress: /quiet
  Log: /log "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 6
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1601
  ReturnResponse: contactSupport
- InstallerReturnCode: 1602
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 1618
  ReturnResponse: installInProgress
- InstallerReturnCode: 1623
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1625
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1628
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1633
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 1638
  ReturnResponse: alreadyInstalled
- InstallerReturnCode: 1639
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1640
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1641
  ReturnResponse: rebootInitiated
- InstallerReturnCode: 1643
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1644
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1649
  ReturnResponse: blockedByPolicy
- InstallerReturnCode: 1650
  ReturnResponse: invalidParameter
- InstallerReturnCode: 1654
  ReturnResponse: systemNotSupported
- InstallerReturnCode: 3010
  ReturnResponse: rebootRequiredToFinish
UpgradeBehavior: install
Protocols:
- foxitpdfreader
- foxitreader
FileExtensions:
- cpdf
- fdf
- pdf
- ppdf
- xdp
- xfdf
ProductCode: '{6C82169A-0BC3-11F0-AEDF-54BF64A63C26}'
ReleaseDate: 2025-08-11
AppsAndFeaturesEntries:
- ProductCode: '{07076c18-fbda-44e6-81c4-4bf87112af2a}'
  UpgradeCode: '{6DEB1C52-84F1-4AB8-A343-08123B2714E2}'
  InstallerType: burn
Installers:
- Architecture: x64
  InstallerUrl: https://cdn01.foxitsoftware.com/product/reader/desktop/win/2025.2.0/FoxitPDFReader20252_L10N_Setup_Prom_x64.exe
  InstallerSha256: 31DB3256B8F5EC55EC9BC5A278A03C938802ED17A61FE6394E196E5FA4FED1BD
ManifestType: installer
ManifestVersion: 1.10.0
