# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Altova.XMLSpy.2025.Professional
PackageVersion: 2026.00.00.00
PackageLocale: en-US
Publisher: Altova
PublisherUrl: https://www.altova.com/
PublisherSupportUrl: https://www.altova.com/support
PrivacyUrl: https://www.altova.com/privacy
Author: Altova GmbH
PackageName: Altova XMLSpy 2025 Professional Edition
PackageUrl: https://www.altova.com/xmlspy-xml-editor
License: Proprietary
LicenseUrl: https://www.altova.com/legal/eula
Copyright: Copyright © 2024 Altova GmbH. All rights reserved.
CopyrightUrl: https://www.altova.com/legal/eula
ShortDescription: JSON and XML Editor
Description: Altova XMLSpy is the world's best selling JSON and XML editor for modeling, editing, transforming, and debugging related technologies. XMLSpy JSON and XML Editor gives developers the tools they need to build the most sophisticated applications with its graphical schema designer, code generation, file converters, debuggers, and profilers for working with XSD, XSLT, XQuery, XBRL, SOAP, and more.
Tags:
- editor
- json
- soap
- xbrl
- xml
- xquery
- xsd
- xslt
PurchaseUrl: https://shop.altova.com/XMLSpy
Documentations:
- DocumentLabel: Documentation
  DocumentUrl: https://www.altova.com/documentation
- DocumentLabel: Training and Tutorials
  DocumentUrl: https://www.altova.com/training-tutorials
ManifestType: defaultLocale
ManifestVersion: 1.10.0
