# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Altova.XMLSpy.2025.Professional
PackageVersion: 2026.00.00.00
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
  InstallLocation: XMLSPYINSTALLDIR="<INSTALLPATH>"
  Log: /L* "<LOGPATH>"
ExpectedReturnCodes:
- InstallerReturnCode: 3
  ReturnResponse: cancelledByUser
- InstallerReturnCode: 6
  ReturnResponse: installInProgress
UpgradeBehavior: install
FileExtensions:
- altova_licenses
- altova_licenses_server
- altova_taxonomies
- altova_xmlschemas
- asp
- avro
- avsc
- biz
- cml
- cpp
- css
- dcd
- dtd
- ent
- epub
- fo
- h
- js
- json
- json5
- jsonc
- jsonl
- jsp
- kml
- kmz
- math
- md
- mml
- pptx
- pxf
- py
- rdf
- smil
- spp
- tld
- txt
- vml
- vxml
- wml
- wsdl
- x3d
- xbr
- xbri
- xbrl
- xdr
- xhtml
- xlsx
- xml
- xq
- xql
- xqr
- xqu
- xquery
- xsd
- xsig
- xsl
- xslt
- xule
- yaml
- yml
- zip
ReleaseDate: 2025-10-20
AppsAndFeaturesEntries:
- InstallerType: msi
Installers:
- InstallerLocale: ja
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026.exe
  InstallerSha256: 4C11DFE95F95AE72EC46F3628DB29270B00E6047999E11A1BF9D11B98EC907F1
  ProductCode: '{F9215D61-D4AF-4E6B-ABA5-CA39B08DB1E0}'
- InstallerLocale: ja
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026_x64.exe
  InstallerSha256: ABA90A9AA2A8152DAD5BA97A6BA9EE77E2CA397FF622B5D38A5DABCDC63A0BF9
  ProductCode: '{EEFDCAD2-9D02-4351-9AD4-31C6BC87DB2C}'
- InstallerLocale: fr
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026.exe
  InstallerSha256: 4C11DFE95F95AE72EC46F3628DB29270B00E6047999E11A1BF9D11B98EC907F1
  ProductCode: '{F9215D61-D4AF-4E6B-ABA5-CA39B08DB1E0}'
- InstallerLocale: fr
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026_x64.exe
  InstallerSha256: ABA90A9AA2A8152DAD5BA97A6BA9EE77E2CA397FF622B5D38A5DABCDC63A0BF9
  ProductCode: '{EEFDCAD2-9D02-4351-9AD4-31C6BC87DB2C}'
- InstallerLocale: es
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026.exe
  InstallerSha256: 4C11DFE95F95AE72EC46F3628DB29270B00E6047999E11A1BF9D11B98EC907F1
  ProductCode: '{F9215D61-D4AF-4E6B-ABA5-CA39B08DB1E0}'
- InstallerLocale: es
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026_x64.exe
  InstallerSha256: ABA90A9AA2A8152DAD5BA97A6BA9EE77E2CA397FF622B5D38A5DABCDC63A0BF9
  ProductCode: '{EEFDCAD2-9D02-4351-9AD4-31C6BC87DB2C}'
- InstallerLocale: en
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026.exe
  InstallerSha256: 4C11DFE95F95AE72EC46F3628DB29270B00E6047999E11A1BF9D11B98EC907F1
  ProductCode: '{F9215D61-D4AF-4E6B-ABA5-CA39B08DB1E0}'
- InstallerLocale: en
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026_x64.exe
  InstallerSha256: ABA90A9AA2A8152DAD5BA97A6BA9EE77E2CA397FF622B5D38A5DABCDC63A0BF9
  ProductCode: '{EEFDCAD2-9D02-4351-9AD4-31C6BC87DB2C}'
- InstallerLocale: de
  Architecture: x86
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026.exe
  InstallerSha256: 4C11DFE95F95AE72EC46F3628DB29270B00E6047999E11A1BF9D11B98EC907F1
  ProductCode: '{F9215D61-D4AF-4E6B-ABA5-CA39B08DB1E0}'
- InstallerLocale: de
  Architecture: x64
  InstallerUrl: https://cdn.sw.altova.com/v2026/en/XMLSpyProf2026_x64.exe
  InstallerSha256: ABA90A9AA2A8152DAD5BA97A6BA9EE77E2CA397FF622B5D38A5DABCDC63A0BF9
  ProductCode: '{EEFDCAD2-9D02-4351-9AD4-31C6BC87DB2C}'
ManifestType: installer
ManifestVersion: 1.10.0
