# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Adobe.Acrobat.Pro.2020
PackageVersion: 20.005.30793
InstallerLocale: en-US
InstallerType: zip
NestedInstallerType: exe
NestedInstallerFiles:
- RelativeFilePath: Adobe Acrobat/setup.exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /sAll /rs /msi
  SilentWithProgress: /sPB /rs /msi
  Interactive: /msi
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
  Log: /log "<LOGPATH>"
  Custom: EULA_ACCEPT=YES
UpgradeBehavior: install
ProductCode: '{AC76BA86-1033-FFFF-7760-0E1401753200}'
ReleaseDate: 2025-09-09
AppsAndFeaturesEntries:
- DisplayName: Adobe Acrobat 2020
  DisplayVersion: 20.001.30002
  ProductCode: '{AC76BA86-1033-FFFF-7760-0E1401753200}'
  UpgradeCode: '{AC76BA86-0000-0000-7760-7E8A45000000}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\Adobe\Acrobat 2020\.'
Installers:
- Architecture: x86
  InstallerUrl: https://trials.adobe.com/AdobeProducts/APRO/Acrobat_HelpX/win32/Acrobat_2020_Web_WWMUI.zip
  InstallerSha256: 83E96A0999FAACF234DA89055039D5E241E202C8439B27B195FDFC8B5D5F3A70
ManifestType: installer
ManifestVersion: 1.10.0

