# Created with Komac v1.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: AnyDeskSoftwareGmbH.AnyDesk
PackageVersion: 8.0.9
InstallerLocale: en-US
Platform:
- Windows.Desktop
InstallerType: msi
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
ReleaseDate: 2024-03-28
Installers:
- Architecture: x86
  InstallerUrl: https://download.anydesk.com/AnyDesk.msi
  InstallerSha256: 38A65E1FDCFADEBFE4AAB74909909CCF70F7744BCE2640AC99F69CA1FB8A0563
  InstallerSwitches:
    Silent: --silent
    SilentWithProgress: --silent
    Upgrade: --remove-first
    Custom: --install "C:\Program Files (x86)\AnyDesk" --update-auto --create-desktop-icon --create-shortcuts
  UpgradeBehavior: install
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk MSI
    ProductCode: AnyDesk
    UpgradeCode: '{ED0600A3-9843-4B5B-B47F-586E1C3FC53A}'
    InstallerType: exe
  ElevationRequirement: elevationRequired
- Architecture: x86
  InstallerUrl: https://download.anydesk.com/AnyDesk.msi
  InstallerSha256: 38A65E1FDCFADEBFE4AAB74909909CCF70F7744BCE2640AC99F69CA1FB8A0563
  UpgradeBehavior: uninstallPrevious
  AppsAndFeaturesEntries:
  - DisplayName: AnyDesk MSI
    ProductCode: '{62853EBF-E9DD-4AA5-B20A-5A6C3DD74FF3}'
    UpgradeCode: '{ED0600A3-9843-4B5B-B47F-586E1C3FC53A}'
    InstallerType: msi
  ElevationRequirement: elevatesSelf
ManifestType: installer
ManifestVersion: 1.5.0
