# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: AmN.yasb
PackageVersion: 1.6.2
InstallerLocale: en-US
InstallerType: msi
ProductCode: '{EA80E2A9-DC6D-4B71-B329-35F80DD5449B}'
ReleaseDate: 2025-02-19
AppsAndFeaturesEntries:
- ProductCode: '{EA80E2A9-DC6D-4B71-B329-35F80DD5449B}'
  UpgradeCode: '{3F620CF5-07B5-47FD-8E37-9CA8AD14B608}'
InstallationMetadata: {}
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/amnweb/yasb/releases/download/v1.6.2/yasb-1.6.2-win64.msi
  InstallerSha256: 0DFB64126817D100D6F0D4D5B50785939095A90B71613234FF265FC023BB15C4
ManifestType: installer
ManifestVersion: 1.9.0
