# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: AmN.yasb
PackageVersion: 1.6.2
PackageLocale: en-US
Publisher: AmN
PublisherUrl: https://github.com/amnweb
PublisherSupportUrl: https://github.com/amnweb/yasb/issues
Author: AmN
PackageName: yasb
PackageUrl: https://github.com/amnweb/yasb
License: MIT License
LicenseUrl: https://github.com/amnweb/yasb/blob/HEAD/LICENSE
Copyright: Copyright 2024 AmN. All rights reserved.
CopyrightUrl: https://github.com/amnweb/yasb/blob/main/LICENSE
ShortDescription: A configurable Windows status bar.
Description: A configurable Windows status bar.
Tags:
- status bar
- topbar
ReleaseNotes: |-
  Bugfixes
  - fix cli reload command 1559c5b
  - update build version to 1.6.2 86fe838
  - prevent processing desktop windows in foreground check 01c3876
  Important
  YASB now reads font names in the same way as Windows. For example, the old font-family: "JetBrainsMono NFP" has become font-family: "JetBrainsMono Nerd Font Propo". To get the correct font name, open the font settings in Windows and copy the font name from there.
  Full Changelog: v1.6.1...v1.6.2
ReleaseNotesUrl: https://github.com/amnweb/yasb/releases/tag/v1.6.2
InstallationNotes: https://github.com/amnweb/yasb
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/amnweb/yasb/wiki
ManifestType: defaultLocale
ManifestVersion: 1.9.0
