# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Dell.CommandUpdate.Universal
PackageVersion: 5.5.0
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /passthrough /S /V/quiet /V/norestart
  SilentWithProgress: /passthrough /V/passive /V/norestart
  Interactive: /passthrough
  InstallLocation: /V"COMMANDUPDATE1=\"<INSTALLPATH>\""
  Log: /V"/log \"<LOGPATH>\""
InstallerSuccessCodes:
- 2
ExpectedReturnCodes:
- InstallerReturnCode: 6
  ReturnResponse: rebootInitiated
UpgradeBehavior: install
ProductCode: '{C7922436-4088-4256-9C99-8E48CC89AA4E}'
ReleaseDate: 2025-03-30
AppsAndFeaturesEntries:
- ProductCode: '{C7922436-4088-4256-9C99-8E48CC89AA4E}'
  UpgradeCode: '{69488F91-BE5B-40E1-9202-CD793CA948ED}'
  InstallerType: msi
Installers:
- Architecture: x64
  InstallerUrl: https://dl.dell.com/FOLDER12925773M/1/Dell-Command-Update-Windows-Universal-Application_P4DJW_WIN64_5.5.0_A00.EXE
  InstallerSha256: 7D46ABC002046D15D005A774123973F232080A51BC13F9CB2E3709CC1BD91E73
ManifestType: installer
ManifestVersion: 1.9.0
