# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: JimRadford.SuperPuTTY
PackageVersion: 1.5.0.0
InstallerLocale: en-US
InstallerType: wix
Scope: machine
ProductCode: '{6948A9B5-8782-4146-A45C-0BAF1C941852}'
ReleaseDate: 2023-01-29
AppsAndFeaturesEntries:
- ProductCode: '{6948A9B5-8782-4146-A45C-0BAF1C941852}'
  UpgradeCode: '{42567F59-2F27-4E5B-A900-9141DC2DD929}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles(x86)%\SuperPuTTY'
Installers:
- Architecture: x86
  InstallerUrl: https://github.com/jimradford/superputty/releases/download/1.5.0.0/SuperPuttySetup-1.5.0.0.msi
  InstallerSha256: 883AAA1520A58BE53CC253A3936B2A8D54BEA08FA07CDABC35272C92AA730163
ManifestType: installer
ManifestVersion: 1.9.0
