# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: DNSCrypt.dnscrypt-proxy
PackageVersion: 2.1.7
PackageLocale: en-US
Publisher: DNSCrypt
PublisherUrl: https://dnscrypt.info/
PublisherSupportUrl: https://github.com/DNSCrypt/dnscrypt-proxy/issues
PackageName: dnscrypt-proxy
PackageUrl: https://github.com/DNSCrypt/dnscrypt-proxy
License: ISC
LicenseUrl: https://github.com/DNSCrypt/dnscrypt-proxy/blob/HEAD/LICENSE
Copyright: Copyright (c) 2018-2023, Frank Denis <j at pureftpd dot org>
CopyrightUrl: https://github.com/DNSCrypt/dnscrypt-proxy/blob/master/LICENSE
ShortDescription: A flexible DNS proxy, with support for modern encrypted DNS protocols
Description: A flexible DNS proxy, with support for modern encrypted DNS protocols such as DNSCrypt v2, DNS-over-HTTPS, Anonymized DNSCrypt and ODoH (Oblivious DoH).
Tags:
- dns
ReleaseNotes: |-
  - This version reintroduces support for XSalsa20 enryption in DNSCrypt, which was removed in 2.1.6. Unfortunately, a bunch of servers still only support that encryption system.
  - A check for lying resolvers was added for DNSCrypt, similar to the one that was already present for DoH and ODoH.
  - Binary packages for Windows/ARM are now available, albeit not in MSI format yet.
ReleaseNotesUrl: https://github.com/DNSCrypt/dnscrypt-proxy/releases/tag/2.1.7
ManifestType: defaultLocale
ManifestVersion: 1.9.0
