# Created with komac v2.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: ExpressVPN.ExpressVPN
PackageVersion: 12.84.0.53
InstallerLocale: en-US
InstallerType: burn
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /install /quiet /norestart
UpgradeBehavior: install
ReleaseDate: 2024-07-18
Installers:
- Architecture: x86
  InstallerUrl: https://www.expressvpn.works/clients/windows/expressvpn_windows_12.84.0.53_release.exe
  InstallerSha256: 6341BDED036ABE12E18E4EB0AFDBA51A90A6BFE5314536AC2073DB8A23C17C14
ManifestType: installer
ManifestVersion: 1.6.0
