# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.PowerToys
PackageVersion: 0.95.1
Platform:
- Windows.Desktop
MinimumOSVersion: 10.0.17134.0
InstallerType: burn
InstallerSwitches:
  Silent: /quiet /norestart
  SilentWithProgress: /quiet /norestart
UpgradeBehavior: install
ReleaseDate: 2025-10-23
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.95.1/PowerToysUserSetup-0.95.1-x64.exe
  InstallerSha256: 637861E7E9B799D21D87068651798893BDF16E927697B87760A2F884122FBCDB
  AppsAndFeaturesEntries:
  - DisplayName: PowerToys (Preview) x64
    ProductCode: '{4A710ED2-300B-4960-A779-125FEDC6C641}'
    UpgradeCode: '{6341382D-C0A9-4238-9188-BE9607E3FAB2}'
    InstallerType: burn
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.95.1/PowerToysSetup-0.95.1-x64.exe
  InstallerSha256: 3C604B200A1E4637AFF98A4129286D309A7DE6E07AA1FDE77E268BC85363570C
  AppsAndFeaturesEntries:
  - DisplayName: PowerToys (Preview) x64
    ProductCode: '{89174DEB-D077-48C6-817C-23B9631E715C}'
    UpgradeCode: '{6341382D-C0A9-4238-9188-BE9607E3FAB2}'
    InstallerType: burn
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\PowerToys'
- Architecture: arm64
  Scope: user
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.95.1/PowerToysUserSetup-0.95.1-arm64.exe
  InstallerSha256: 90DC594E071BB0FD5797FE73B55F4E29F40F4B5B8CE6F13C1DBECCC8C7129F58
  AppsAndFeaturesEntries:
  - DisplayName: PowerToys (Preview) ARM64
    ProductCode: '{6210F7A2-ACFB-4805-BCD3-23B14AF22DB7}'
    UpgradeCode: '{6341382D-C0A9-4238-9188-BE9607E3FAB2}'
    InstallerType: burn
- Architecture: arm64
  Scope: machine
  InstallerUrl: https://github.com/microsoft/PowerToys/releases/download/v0.95.1/PowerToysSetup-0.95.1-arm64.exe
  InstallerSha256: A69BF84D1F627F8576DE5102FB293BDAACF5FD6AC821DDCB64EDC3327C446A2F
  AppsAndFeaturesEntries:
  - DisplayName: PowerToys (Preview) ARM64
    ProductCode: '{FDBB1691-794B-4894-8416-326DA92F4F7A}'
    UpgradeCode: '{6341382D-C0A9-4238-9188-BE9607E3FAB2}'
    InstallerType: burn
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\PowerToys'
ManifestType: installer
ManifestVersion: 1.10.0
