# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: Microsoft.PowerToys
PackageVersion: 0.95.1
PackageLocale: en-US
Publisher: Microsoft Corporation
PublisherUrl: https://github.com/microsoft/PowerToys
PublisherSupportUrl: https://github.com/microsoft/PowerToys/issues
PrivacyUrl: https://privacy.microsoft.com/en-us/privacystatement
Author: Microsoft Corporation
PackageName: PowerToys
PackageUrl: https://github.com/microsoft/PowerToys
License: MIT
LicenseUrl: https://github.com/microsoft/PowerToys/blob/HEAD/LICENSE
Copyright: Copyright (c) Microsoft Corporation. All rights reserved.
CopyrightUrl: https://github.com/microsoft/PowerToys/blob/main/LICENSE
ShortDescription: Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows experience for greater productivity.
Description: |-
  Microsoft PowerToys is a set of utilities for power users to tune and streamline their Windows experience for greater productivity.
  Inspired by the Windows 95 era PowerToys project, this reboot provides power users with ways to squeeze more efficiency out of the Windows 10 shell and customize it for individual workflows.
Moniker: powertoys
Tags:
- colorpicker
- fancyzones
- fileexplorer
- imageresizer
- keyboardmanager
- power-toys
- powerrename
- powertoys
- powertoys-run
- windows-key-shortcut-guide
ReleaseNotes: |-
  This patch release fixes several important stability issues identified in v0.95.0 based on incoming reports. Check out the v0.95.0 notes for the full list of changes.
  Installer Hashes
  ────────────────────┬────────────────────────────────────────
  Description         │Filename
  ────────────────────┼────────────────────────────────────────
  Per user - x64      │PowerToysUserSetup-0.95.1-x64.exe
  ────────────────────┼────────────────────────────────────────
  Per user - ARM64    │PowerToysUserSetup-0.95.1-arm64.exe
  ────────────────────┼────────────────────────────────────────
  Machine wide - x64  │PowerToysSetup-0.95.1-x64.exe
  ────────────────────┼────────────────────────────────────────
  Machine wide - ARM64│PowerToysSetup-0.95.1-arm64.exe
  ────────────────────┴────────────────────────────────────────
  Highlights
  Light Switch
  ⚠️ NOTE: If you encountered issues with light/dark theme switching before this update, try turning Light Switch off and back on to reset it. ⚠️
  - #42434: Fixed bug where Light Switch was enabled by default
  - #42434: Fixed bug where Manual time schedule was being overridden by sunset calculations
  - #42434: Renamed "Manual" mode to "Fixed Hours" for clarity
  - #42434: Created a new "Off" mode that disables the schedule but still allows the shortcut to be used
  - #42434: Fixed a bug which allowed the taskbar to be the accent color in light mode (this should only be allowed in dark mode)
  - #42774: Fixed a bug where light/dark times where not updating when switch between modes (Specifically manual back to Sunset to Sunrise mode).
  CmdPal
  - #42467: Fixed crashes on pages using filters (e.g., Windows Terminal profiles, Windows Services) when built with trimming or AOT by removing runtime bindings from the FiltersDropDown control.
  - #42405: Fixed an issue where window style changes (such as WS_EX_TOOLWINDOW) were not properly applied by ensuring cached window data is refreshed.
  Find my mouse:
  - #42774: Fixed bug that would cause the window to lose focus
  - #42774: Fixed bug that would cause the mouse to go busy (hourglass)
  Installer:
  - #41975: Removed WiX v3 infrastructure and migrate exclusively to WiX v5, cutting build times.
  Bug report:
  - #42399: Improvements to the bug report system
ReleaseNotesUrl: https://github.com/microsoft/PowerToys/releases/tag/v0.95.1
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/microsoft/PowerToys/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
