# Created using wingetcreate 1.6.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Citrix.Workspace
PackageVersion: 24.5.10.29
InstallerType: exe
Scope: machine
InstallModes:
- interactive
- silent
InstallerSwitches:
  Silent: /silent /norestart
  SilentWithProgress: /silent /norestart
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Protocols:
- receiver
FileExtensions:
- cr
- ica
ProductCode: CitrixOnlinePluginPackWeb
Installers:
- Architecture: x86
  InstallerUrl: https://downloadplugins.citrix.com/ReceiverUpdates/Prod/Receiver/Win/CitrixWorkspaceApp24.5.10.29.exe
  InstallerSha256: 8F161CA2FD8E6B8911F730F1404BACCBFE7A3E0DB7416A07FE9DE165FD39666E
ManifestType: installer
ManifestVersion: 1.6.0
