# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: ransome1.sleek
PackageVersion: 2.0.16
InstallerLocale: en-US
InstallModes:
- silent
ReleaseDate: 2025-01-19
Installers:
- Architecture: x64
  InstallerType: nullsoft
  Scope: user
  InstallerUrl: https://github.com/ransome1/sleek/releases/download/v2.0.16/sleek-2.0.16-win-x64.exe
  InstallerSha256: 9305BF7328D0AAAB05AECAFDD27986F599F8BD48F6F6E684091ACB2275D5D0D4
  UpgradeBehavior: install
- Architecture: x64
  InstallerType: portable
  InstallerUrl: https://github.com/ransome1/sleek/releases/download/v2.0.16/sleek-2.0.16-win-x64.exe
  InstallerSha256: 9305BF7328D0AAAB05AECAFDD27986F599F8BD48F6F6E684091ACB2275D5D0D4
ManifestType: installer
ManifestVersion: 1.9.0
