# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Amazon.Corretto.21.JDK
PackageVersion: 24.0.0.36
InstallerLocale: en-US
InstallerType: wix
Scope: machine
InstallerSwitches:
  InstallLocation: INSTALLDIR="<INSTALLPATH>"
UpgradeBehavior: install
Commands:
- jar
- jarsigner
- java
- javac
- javadoc
- javap
- javaw
- jconsole
- jdeprscan
- jdeps
- jlink
- jmod
- jps
- jshell
- jstat
- keytool
FileExtensions:
- class
- jar
- java
- jsp
ProductCode: '{09D8E817-BE84-4E9C-BFE1-A223E18B15EE}'
ReleaseDate: 2025-02-10
AppsAndFeaturesEntries:
- DisplayName: Amazon Corretto (x64)
  ProductCode: '{09D8E817-BE84-4E9C-BFE1-A223E18B15EE}'
  UpgradeCode: '{3EEF11EA-DDFA-4BF4-A5ED-DDCA47D0628C}'
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%\Amazon Corretto'
Installers:
- Architecture: x64
  InstallerUrl: https://corretto.aws/downloads/resources/24.0.0.36.1/amazon-corretto-24.0.0.36.1-windows-x64.msi
  InstallerSha256: F02217A650093D47169047C9CD77B35F5705BEDEA4B2A9BAA30D793F331070B1
ManifestType: installer
ManifestVersion: 1.9.0
