# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: MicroSIP.MicroSIP
PackageVersion: 3.22.2
PackageLocale: en-US
Publisher: www.microsip.org
PublisherUrl: https://www.microsip.org/
PublisherSupportUrl: https://www.microsip.org/help
PackageName: MicroSIP
PackageUrl: https://www.microsip.org/downloads
License: GPL-2.0
LicenseUrl: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
Copyright: MicroSIP
ShortDescription: Open source portable SIP softphone based on PJSIP stack for Windows OS.
Description: |-
  MicroSIP - open source portable SIP softphone based on PJSIP stack for Windows OS.
  It allowing to do high quality VoIP calls (person-to-person or on regular telephones) via open SIP protocol. From cloud of SIP providers you can choose best for you, register account and use it with MicroSIP. You'll get free person-to-person calls and cheap international calls.
Moniker: microsip
Tags:
- pbx
- sip
- softphone
- telephone
- telephony
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://www.microsip.org/faq
- DocumentLabel: Troubleshooting
  DocumentUrl: https://www.microsip.org/issues
ManifestType: defaultLocale
ManifestVersion: 1.10.0
