# Created with komac v2.12.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: MicroSIP.MicroSIP
PackageVersion: 3.22.2
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
UpgradeBehavior: install
Protocols:
- callto
- dial
- dialpad
- sip
- tel
ProductCode: MicroSIP
ReleaseDate: 2025-09-05
AppsAndFeaturesEntries:
- {}
InstallationMetadata:
  DefaultInstallLocation: '%LocalAppData%\MicroSIP'
Installers:
- Architecture: x86
  InstallerUrl: https://www.microsip.org/download/MicroSIP-3.22.2.exe
  InstallerSha256: 40365E8C08F3EA62C65AF18C5D13162FD4F307BAF79726C747D201CFFC4B737B
ManifestType: installer
ManifestVersion: 1.10.0
