# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: PocketSync.PocketSync
PackageVersion: 7.0.1
InstallerLocale: en-US
InstallerType: nullsoft
Scope: user
InstallerSwitches:
  Silent: /S
UpgradeBehavior: install
ProductCode: Pocket Sync
ReleaseDate: 2026-10-10
AppsAndFeaturesEntries:
- Publisher: neil
  ProductCode: Pocket Sync
InstallationMetadata:
  DefaultInstallLocation: "%LocalAppData%\\Pocket Sync"
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/neil-morrison44/pocket-sync/releases/download/v7.0.1/Pocket.Sync_7.0.1_x64-setup.exe
  InstallerSha256: 423CFE27A32B53F043A0183E744A0309D74E1598FCF642507C520FCC08FE0CED
ManifestType: installer
ManifestVersion: 1.12.0
