# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json
# Created with winmatsch

PackageIdentifier: PocketSync.PocketSync
PackageVersion: 7.0.1
PackageLocale: en-US
Publisher: Pocket Sync
PublisherUrl: https://github.com/neil-morrison44/pocket-sync
PublisherSupportUrl: https://github.com/neil-morrison44/pocket-sync/issues
Author: neil-morrison44
PackageName: Pocket Sync
PackageUrl: https://github.com/neil-morrison44/pocket-sync/releases/download/v4.12.0/Pocket.Sync_4.12.0_x64-setup.exe
License: AGPL-3.0
LicenseUrl: https://github.com/neil-morrison44/pocket-sync/blob/HEAD/LICENSE.md
ShortDescription: Pocket Sync
Moniker: pocketsync
Tags:
- analogue-pocket-sync
ReleaseNotes: |-
  ## What's Changed
  • Bump actions/checkout from 6 to 7 by @dependabot[bot] in https://github.com/neil-morrison44/pocket-sync/pull/471
  • Bump actions/deploy-pages from 4 to 5 by @dependabot[bot] in https://github.com/neil-morrison44/pocket-sync/pull/470
  • Bump tauri-apps/tauri-action from 0.6.0 to 1.0.0 by @dependabot[bot] in https://github.com/neil-morrison44/pocket-sync/pull/472
  • Bump actions/upload-artifact from 5 to 7 by @dependabot[bot] in https://github.com/neil-morrison44/pocket-sync/pull/447
  • Bump actions/github-script from 8 to 9 by @dependabot[bot] in https://github.com/neil-morrison44/pocket-sync/pull/445
  • Fix image packs by @neil-morrison44 in https://github.com/neil-morrison44/pocket-sync/pull/487


  **Full Changelog**：https://github.com/neil-morrison44/pocket-sync/compare/v7.0.0...v7.0.1
ReleaseNotesUrl: https://github.com/neil-morrison44/pocket-sync/releases/tag/v7.0.1
ManifestType: defaultLocale
ManifestVersion: 1.12.0
