# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: CatoNetworks.CatoClient
PackageVersion: 5.14.5.5557
PackageLocale: en-US
Publisher: Cato Networks
PackageName: Cato Client
License: proprietary
Copyright: Copyright (c) 2022 Cato Networks
ShortDescription: Cato Networks VPN
ManifestType: defaultLocale
ManifestVersion: 1.9.0
