# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.9.0.schema.json

PackageIdentifier: FleetingClarityStudios.QuickFixMyPic
PackageVersion: 1.0.3.0
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.9.0
