# Created with komac v2.11.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: FleetingClarityStudios.QuickFixMyPic
PackageVersion: 1.0.3.0
PackageLocale: en-US
Publisher: FleetingClarityStudios
PublisherUrl: https://github.com/Echostorm44
PublisherSupportUrl: https://github.com/Echostorm44/QuickFixMyPic/issues
PackageName: QuickFixMyPic
PackageUrl: https://github.com/Echostorm44/QuickFixMyPic
License: GPL-3.0
LicenseUrl: https://github.com/Echostorm44/QuickFixMyPic/blob/HEAD/LICENSE
ShortDescription: A simple utility to batch convert and or resize images
ReleaseNotes: Changes to make ICO generation more bullet proof and windows compat
ReleaseNotesUrl: https://github.com/Echostorm44/QuickFixMyPic/releases/tag/1.0.3.0
ManifestType: defaultLocale
ManifestVersion: 1.9.0
