# Created with komac v2.10.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: FleetingClarityStudios.QuickFixMyPic
PackageVersion: 1.0.3.0
InstallerLocale: en-US
InstallerType: msi
Scope: user
ProductCode: '{5CD4F431-CEE2-45B3-AD60-A120BCDC0DBC}'
ReleaseDate: 2022-10-14
AppsAndFeaturesEntries:
- ProductCode: '{5CD4F431-CEE2-45B3-AD60-A120BCDC0DBC}'
  UpgradeCode: '{713331A2-8317-4635-91A8-B1AC06C2794D}'
InstallationMetadata:
  DefaultInstallLocation: runtimes
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Echostorm44/QuickFixMyPic/releases/download/1.0.3.0/SetupQuickFixMyPic.msi
  InstallerSha256: 2313EB3A54DE8D6FA78BC39964F4505FC5A63A15EC501237B0D78A99596D00C7
ManifestType: installer
ManifestVersion: 1.9.0
